//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoCreateRecord_Input: Codable, Sendable {
        public var collection: String
        public var record: LexiconTypeDecoder
        public var repo: String
        public var rkey: String?
        public var swapCommit: String?
        public var validate: Bool?
        public var _unknownValues: [String: AnyCodable]

        public init(collection: String, record: LexiconTypeDecoder, repo: String, rkey: String? = nil, swapCommit: String? = nil, validate: Bool? = nil) {
            self.collection = collection
            self.record = record
            self.repo = repo
            self.rkey = rkey
            self.swapCommit = swapCommit
            self.validate = validate
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case collection
            case record
            case repo
            case rkey
            case swapCommit
            case validate
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.collection = try keyedContainer.decode(String.self, forKey: .collection)
            self.record = try keyedContainer.decode(LexiconTypeDecoder.self, forKey: .record)
            self.repo = try keyedContainer.decode(String.self, forKey: .repo)
            self.rkey = try keyedContainer.decodeIfPresent(String.self, forKey: .rkey)
            self.swapCommit = try keyedContainer.decodeIfPresent(String.self, forKey: .swapCommit)
            self.validate = try keyedContainer.decodeIfPresent(Bool.self, forKey: .validate)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.collection, forKey: .collection)
            try container.encode(self.record, forKey: .record)
            try container.encode(self.repo, forKey: .repo)
            try container.encodeIfPresent(self.rkey, forKey: .rkey)
            try container.encodeIfPresent(self.swapCommit, forKey: .swapCommit)
            try container.encodeIfPresent(self.validate, forKey: .validate)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoCreateRecord_Output: Codable, Sendable {
        public var cid: String
        public var commit: RepoDefs_CommitMeta?
        public var uri: String
        public var validationStatus: RepoCreateRecord_Output_ValidationStatus?
        public var _unknownValues: [String: AnyCodable]

        public init(cid: String, commit: RepoDefs_CommitMeta? = nil, uri: String, validationStatus: RepoCreateRecord_Output_ValidationStatus? = nil) {
            self.cid = cid
            self.commit = commit
            self.uri = uri
            self.validationStatus = validationStatus
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case commit
            case uri
            case validationStatus
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.commit = try keyedContainer.decodeIfPresent(RepoDefs_CommitMeta.self, forKey: .commit)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.validationStatus = try keyedContainer.decodeIfPresent(RepoCreateRecord_Output_ValidationStatus.self, forKey: .validationStatus)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cid, forKey: .cid)
            try container.encodeIfPresent(self.commit, forKey: .commit)
            try container.encode(self.uri, forKey: .uri)
            try container.encodeIfPresent(self.validationStatus, forKey: .validationStatus)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoCreateRecord_Output_ValidationStatus: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case valid
        case unknown
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "valid":
                self = .valid
            case "unknown":
                self = .unknown
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .valid:
                "valid"
            case .unknown:
                "unknown"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum RepoCreateRecord_Error: XRPCError {
        case invalidswap(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "InvalidSwap":
                self = .invalidswap(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .invalidswap:
                return "InvalidSwap"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .invalidswap(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoCreateRecord(input: comatprototypes.RepoCreateRecord_Input) async throws -> comatprototypes.RepoCreateRecord_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.repo.createRecord", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoCreateRecord_Error(error: error)
        }
    }
}
