//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerRequestEmailUpdate_Output: Codable, Sendable {
        public var tokenRequired: Bool
        public var _unknownValues: [String: AnyCodable]

        public init(tokenRequired: Bool) {
            self.tokenRequired = tokenRequired
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case tokenRequired
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.tokenRequired = try keyedContainer.decode(Bool.self, forKey: .tokenRequired)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.tokenRequired, forKey: .tokenRequired)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerRequestEmailUpdate_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerRequestEmailUpdate() async throws -> comatprototypes.ServerRequestEmailUpdate_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.requestEmailUpdate", contentType: "*/*", httpMethod: .post, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerRequestEmailUpdate_Error(error: error)
        }
    }
}
