//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct SyncGetRepoStatus_Output: Codable, Sendable {
        public var active: Bool
        public var did: String
        public var rev: String?
        public var status: SyncGetRepoStatus_Output_Status?
        public var _unknownValues: [String: AnyCodable]

        public init(active: Bool, did: String, rev: String? = nil, status: SyncGetRepoStatus_Output_Status? = nil) {
            self.active = active
            self.did = did
            self.rev = rev
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case active
            case did
            case rev
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.active = try keyedContainer.decode(Bool.self, forKey: .active)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.rev = try keyedContainer.decodeIfPresent(String.self, forKey: .rev)
            self.status = try keyedContainer.decodeIfPresent(SyncGetRepoStatus_Output_Status.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.active, forKey: .active)
            try container.encode(self.did, forKey: .did)
            try container.encodeIfPresent(self.rev, forKey: .rev)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncGetRepoStatus_Output_Status: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case takendown
        case suspended
        case deleted
        case deactivated
        case desynchronized
        case throttled
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deleted":
                self = .deleted
            case "deactivated":
                self = .deactivated
            case "desynchronized":
                self = .desynchronized
            case "throttled":
                self = .throttled
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deleted:
                "deleted"
            case .deactivated:
                "deactivated"
            case .desynchronized:
                "desynchronized"
            case .throttled:
                "throttled"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum SyncGetRepoStatus_Error: XRPCError {
        case reponotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "RepoNotFound":
                self = .reponotfound(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .reponotfound:
                return "RepoNotFound"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .reponotfound(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func SyncGetRepoStatus(did: String) async throws -> comatprototypes.SyncGetRepoStatus_Output {
        let params: Parameters = ["did": .string(did)]
        do {
            return try await fetch(endpoint: "com.atproto.sync.getRepoStatus", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.SyncGetRepoStatus_Error(error: error)
        }
    }
}
