//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct SyncListRepos_Output: Codable, Sendable {
        public var cursor: String?
        public var repos: [SyncListRepos_Repo]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, repos: [SyncListRepos_Repo]) {
            self.cursor = cursor
            self.repos = repos
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case repos
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.repos = try keyedContainer.decode([SyncListRepos_Repo].self, forKey: .repos)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.repos, forKey: .repos)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct SyncListRepos_Repo: Codable, Sendable {
        public var active: Bool?
        public var did: String
        public var head: String
        public var rev: String
        public var status: SyncListRepos_Repo_Status?
        public let _unknownValues: [String: AnyCodable]

        public init(active: Bool? = nil, did: String, head: String, rev: String, status: SyncListRepos_Repo_Status? = nil) {
            self.active = active
            self.did = did
            self.head = head
            self.rev = rev
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case active
            case did
            case head
            case rev
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.active = try keyedContainer.decodeIfPresent(Bool.self, forKey: .active)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.head = try keyedContainer.decode(String.self, forKey: .head)
            self.rev = try keyedContainer.decode(String.self, forKey: .rev)
            self.status = try keyedContainer.decodeIfPresent(SyncListRepos_Repo_Status.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.active, forKey: .active)
            try container.encode(self.did, forKey: .did)
            try container.encode(self.head, forKey: .head)
            try container.encode(self.rev, forKey: .rev)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncListRepos_Repo_Status: RawRepresentable, Codable, Sendable {
        case takendown
        case suspended
        case deleted
        case deactivated
        case desynchronized
        case throttled
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deleted":
                self = .deleted
            case "deactivated":
                self = .deactivated
            case "desynchronized":
                self = .desynchronized
            case "throttled":
                self = .throttled
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deleted:
                "deleted"
            case .deactivated:
                "deactivated"
            case .desynchronized:
                "desynchronized"
            case .throttled:
                "throttled"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum SyncListRepos_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func SyncListRepos(cursor: String? = nil, limit: Int? = nil) async throws -> comatprototypes.SyncListRepos_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "com.atproto.sync.listRepos", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.SyncListRepos_Error(error: error)
        }
    }
}
