//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoGetRecord_Output: Codable, Sendable {
        public var cid: String?
        public var uri: String
        public var value: LexiconTypeDecoder
        public var _unknownValues: [String: AnyCodable]

        public init(cid: String? = nil, uri: String, value: LexiconTypeDecoder) {
            self.cid = cid
            self.uri = uri
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case uri
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decodeIfPresent(String.self, forKey: .cid)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.value = try keyedContainer.decode(LexiconTypeDecoder.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cid, forKey: .cid)
            try container.encode(self.uri, forKey: .uri)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoGetRecord_Error: XRPCError {
        case recordnotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "RecordNotFound":
                self = .recordnotfound(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .recordnotfound:
                return "RecordNotFound"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .recordnotfound(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoGetRecord(cid: String? = nil, collection: String, repo: String, rkey: String) async throws -> comatprototypes.RepoGetRecord_Output {
        let params: Parameters = ["cid": .string(cid), "collection": .string(collection), "repo": .string(repo), "rkey": .string(rkey)]
        do {
            return try await fetch(endpoint: "com.atproto.repo.getRecord", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoGetRecord_Error(error: error)
        }
    }
}
