//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerCreateInviteCode_Input: Codable, Sendable {
        public var forAccount: String?
        public var useCount: Int
        public var _unknownValues: [String: AnyCodable]

        public init(forAccount: String? = nil, useCount: Int) {
            self.forAccount = forAccount
            self.useCount = useCount
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case forAccount
            case useCount
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.forAccount = try keyedContainer.decodeIfPresent(String.self, forKey: .forAccount)
            self.useCount = try keyedContainer.decode(Int.self, forKey: .useCount)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.forAccount, forKey: .forAccount)
            try container.encode(self.useCount, forKey: .useCount)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerCreateInviteCode_Output: Codable, Sendable {
        public var code: String
        public var _unknownValues: [String: AnyCodable]

        public init(code: String) {
            self.code = code
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case code
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.code = try keyedContainer.decode(String.self, forKey: .code)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.code, forKey: .code)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerCreateInviteCode_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerCreateInviteCode(input: comatprototypes.ServerCreateInviteCode_Input) async throws -> comatprototypes.ServerCreateInviteCode_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.createInviteCode", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerCreateInviteCode_Error(error: error)
        }
    }
}
