//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct AdminSendEmail_Input: Codable, Sendable {
        public var comment: String?
        public var content: String
        public var recipientDid: String
        public var senderDid: String
        public var subject: String?
        public let _unknownValues: [String: AnyCodable]

        public init(comment: String? = nil, content: String, recipientDid: String, senderDid: String, subject: String? = nil) {
            self.comment = comment
            self.content = content
            self.recipientDid = recipientDid
            self.senderDid = senderDid
            self.subject = subject
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case comment
            case content
            case recipientDid
            case senderDid
            case subject
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.comment = try keyedContainer.decodeIfPresent(String.self, forKey: .comment)
            self.content = try keyedContainer.decode(String.self, forKey: .content)
            self.recipientDid = try keyedContainer.decode(String.self, forKey: .recipientDid)
            self.senderDid = try keyedContainer.decode(String.self, forKey: .senderDid)
            self.subject = try keyedContainer.decodeIfPresent(String.self, forKey: .subject)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.comment, forKey: .comment)
            try container.encode(self.content, forKey: .content)
            try container.encode(self.recipientDid, forKey: .recipientDid)
            try container.encode(self.senderDid, forKey: .senderDid)
            try container.encodeIfPresent(self.subject, forKey: .subject)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct AdminSendEmail_Output: Codable, Sendable {
        public var sent: Bool
        public let _unknownValues: [String: AnyCodable]

        public init(sent: Bool) {
            self.sent = sent
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case sent
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.sent = try keyedContainer.decode(Bool.self, forKey: .sent)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.sent, forKey: .sent)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminSendEmail_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func AdminSendEmail(input: comatprototypes.AdminSendEmail_Input) async throws -> comatprototypes.AdminSendEmail_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.admin.sendEmail", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.AdminSendEmail_Error(error: error)
        }
    }
}
