//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct AdminEnableAccountInvites_Input: Codable, Sendable {
        public var account: String
        public var note: String?
        public var _unknownValues: [String: AnyCodable]

        public init(account: String, note: String? = nil) {
            self.account = account
            self.note = note
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case account
            case note
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.account = try keyedContainer.decode(String.self, forKey: .account)
            self.note = try keyedContainer.decodeIfPresent(String.self, forKey: .note)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.account, forKey: .account)
            try container.encodeIfPresent(self.note, forKey: .note)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminEnableAccountInvites_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func AdminEnableAccountInvites(input: comatprototypes.AdminEnableAccountInvites_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.admin.enableAccountInvites", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.AdminEnableAccountInvites_Error(error: error)
        }
    }
}
