//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct TempFetchLabels_Output: Codable, Sendable {
        public var labels: [LabelDefs_Label]
        public let _unknownValues: [String: AnyCodable]

        public init(labels: [LabelDefs_Label]) {
            self.labels = labels
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case labels
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.labels = try keyedContainer.decode([LabelDefs_Label].self, forKey: .labels)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.labels, forKey: .labels)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum TempFetchLabels_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func TempFetchLabels(limit: Int? = nil, since: Int? = nil) async throws -> comatprototypes.TempFetchLabels_Output {
        let params: Parameters = ["limit": .integer(limit), "since": .integer(since)]
        do {
            return try await fetch(endpoint: "com.atproto.temp.fetchLabels", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.TempFetchLabels_Error(error: error)
        }
    }
}
