//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct TempAddReservedHandle_Input: Codable, Sendable {
        public var handle: String
        public let _unknownValues: [String: AnyCodable]

        public init(handle: String) {
            self.handle = handle
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case handle
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.handle = try keyedContainer.decode(String.self, forKey: .handle)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.handle, forKey: .handle)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct TempAddReservedHandle_Output: Codable, Sendable {
        public let _unknownValues: [String: AnyCodable]

        public init() {
            self._unknownValues = [:]
        }

        public init(from decoder: any Decoder) throws {
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum TempAddReservedHandle_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func TempAddReservedHandle(input: comatprototypes.TempAddReservedHandle_Input) async throws -> comatprototypes.TempAddReservedHandle_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.temp.addReservedHandle", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.TempAddReservedHandle_Error(error: error)
        }
    }
}
