//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoDeleteRecord_Input: Codable, Sendable {
        public var collection: String
        public var repo: String
        public var rkey: String
        public var swapCommit: String?
        public var swapRecord: String?
        public let _unknownValues: [String: AnyCodable]

        public init(collection: String, repo: String, rkey: String, swapCommit: String? = nil, swapRecord: String? = nil) {
            self.collection = collection
            self.repo = repo
            self.rkey = rkey
            self.swapCommit = swapCommit
            self.swapRecord = swapRecord
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case collection
            case repo
            case rkey
            case swapCommit
            case swapRecord
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.collection = try keyedContainer.decode(String.self, forKey: .collection)
            self.repo = try keyedContainer.decode(String.self, forKey: .repo)
            self.rkey = try keyedContainer.decode(String.self, forKey: .rkey)
            self.swapCommit = try keyedContainer.decodeIfPresent(String.self, forKey: .swapCommit)
            self.swapRecord = try keyedContainer.decodeIfPresent(String.self, forKey: .swapRecord)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.collection, forKey: .collection)
            try container.encode(self.repo, forKey: .repo)
            try container.encode(self.rkey, forKey: .rkey)
            try container.encodeIfPresent(self.swapCommit, forKey: .swapCommit)
            try container.encodeIfPresent(self.swapRecord, forKey: .swapRecord)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoDeleteRecord_Output: Codable, Sendable {
        public var commit: RepoDefs_CommitMeta?
        public let _unknownValues: [String: AnyCodable]

        public init(commit: RepoDefs_CommitMeta? = nil) {
            self.commit = commit
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case commit
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.commit = try keyedContainer.decodeIfPresent(RepoDefs_CommitMeta.self, forKey: .commit)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.commit, forKey: .commit)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoDeleteRecord_Error: XRPCError {
        case invalidswap(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "InvalidSwap":
                self = .invalidswap(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .invalidswap:
                return "InvalidSwap"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .invalidswap(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoDeleteRecord(input: comatprototypes.RepoDeleteRecord_Input) async throws -> comatprototypes.RepoDeleteRecord_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.repo.deleteRecord", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoDeleteRecord_Error(error: error)
        }
    }
}
