//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct IdentitySignPlcOperation_Input: Codable, Sendable {
        public var alsoKnownAs: [String]?
        public var rotationKeys: [String]?
        public var services: LexiconTypeDecoder?
        public var token: String?
        public var verificationMethods: LexiconTypeDecoder?
        public var _unknownValues: [String: AnyCodable]

        public init(alsoKnownAs: [String]? = nil, rotationKeys: [String]? = nil, services: LexiconTypeDecoder? = nil, token: String? = nil, verificationMethods: LexiconTypeDecoder? = nil) {
            self.alsoKnownAs = alsoKnownAs
            self.rotationKeys = rotationKeys
            self.services = services
            self.token = token
            self.verificationMethods = verificationMethods
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case alsoKnownAs
            case rotationKeys
            case services
            case token
            case verificationMethods
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.alsoKnownAs = try keyedContainer.decodeIfPresent([String].self, forKey: .alsoKnownAs)
            self.rotationKeys = try keyedContainer.decodeIfPresent([String].self, forKey: .rotationKeys)
            self.services = try keyedContainer.decodeIfPresent(LexiconTypeDecoder.self, forKey: .services)
            self.token = try keyedContainer.decodeIfPresent(String.self, forKey: .token)
            self.verificationMethods = try keyedContainer.decodeIfPresent(LexiconTypeDecoder.self, forKey: .verificationMethods)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.alsoKnownAs, forKey: .alsoKnownAs)
            try container.encodeIfPresent(self.rotationKeys, forKey: .rotationKeys)
            try container.encodeIfPresent(self.services, forKey: .services)
            try container.encodeIfPresent(self.token, forKey: .token)
            try container.encodeIfPresent(self.verificationMethods, forKey: .verificationMethods)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct IdentitySignPlcOperation_Output: Codable, Sendable {
        public var operation: LexiconTypeDecoder
        public var _unknownValues: [String: AnyCodable]

        public init(operation: LexiconTypeDecoder) {
            self.operation = operation
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case operation
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.operation = try keyedContainer.decode(LexiconTypeDecoder.self, forKey: .operation)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.operation, forKey: .operation)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum IdentitySignPlcOperation_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func IdentitySignPlcOperation(input: comatprototypes.IdentitySignPlcOperation_Input) async throws -> comatprototypes.IdentitySignPlcOperation_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.identity.signPlcOperation", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.IdentitySignPlcOperation_Error(error: error)
        }
    }
}
