//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerGetAccountInviteCodes_Output: Codable, Sendable {
        public var codes: [ServerDefs_InviteCode]
        public var _unknownValues: [String: AnyCodable]

        public init(codes: [ServerDefs_InviteCode]) {
            self.codes = codes
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case codes
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.codes = try keyedContainer.decode([ServerDefs_InviteCode].self, forKey: .codes)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.codes, forKey: .codes)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerGetAccountInviteCodes_Error: XRPCError {
        case duplicatecreate(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "DuplicateCreate":
                self = .duplicatecreate(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .duplicatecreate:
                return "DuplicateCreate"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .duplicatecreate(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerGetAccountInviteCodes(createAvailable: Bool? = nil, includeUsed: Bool? = nil) async throws -> comatprototypes.ServerGetAccountInviteCodes_Output {
        let params: Parameters = ["createAvailable": .bool(createAvailable), "includeUsed": .bool(includeUsed)]
        do {
            return try await fetch(endpoint: "com.atproto.server.getAccountInviteCodes", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerGetAccountInviteCodes_Error(error: error)
        }
    }
}
