//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerDescribeServer_Contact: Codable, Sendable {
        public var email: String?
        public var _unknownValues: [String: AnyCodable]

        public init(email: String? = nil) {
            self.email = email
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case email
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.email = try keyedContainer.decodeIfPresent(String.self, forKey: .email)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.email, forKey: .email)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerDescribeServer_Links: Codable, Sendable {
        public var privacyPolicy: String?
        public var termsOfService: String?
        public var _unknownValues: [String: AnyCodable]

        public init(privacyPolicy: String? = nil, termsOfService: String? = nil) {
            self.privacyPolicy = privacyPolicy
            self.termsOfService = termsOfService
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case privacyPolicy
            case termsOfService
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.privacyPolicy = try keyedContainer.decodeIfPresent(String.self, forKey: .privacyPolicy)
            self.termsOfService = try keyedContainer.decodeIfPresent(String.self, forKey: .termsOfService)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.privacyPolicy, forKey: .privacyPolicy)
            try container.encodeIfPresent(self.termsOfService, forKey: .termsOfService)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerDescribeServer_Output: Codable, Sendable {
        public var availableUserDomains: [String]
        public var contact: ServerDescribeServer_Contact?
        public var did: String
        public var inviteCodeRequired: Bool?
        public var links: ServerDescribeServer_Links?
        public var phoneVerificationRequired: Bool?
        public var _unknownValues: [String: AnyCodable]

        public init(availableUserDomains: [String], contact: ServerDescribeServer_Contact? = nil, did: String, inviteCodeRequired: Bool? = nil, links: ServerDescribeServer_Links? = nil, phoneVerificationRequired: Bool? = nil) {
            self.availableUserDomains = availableUserDomains
            self.contact = contact
            self.did = did
            self.inviteCodeRequired = inviteCodeRequired
            self.links = links
            self.phoneVerificationRequired = phoneVerificationRequired
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case availableUserDomains
            case contact
            case did
            case inviteCodeRequired
            case links
            case phoneVerificationRequired
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.availableUserDomains = try keyedContainer.decode([String].self, forKey: .availableUserDomains)
            self.contact = try keyedContainer.decodeIfPresent(ServerDescribeServer_Contact.self, forKey: .contact)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.inviteCodeRequired = try keyedContainer.decodeIfPresent(Bool.self, forKey: .inviteCodeRequired)
            self.links = try keyedContainer.decodeIfPresent(ServerDescribeServer_Links.self, forKey: .links)
            self.phoneVerificationRequired = try keyedContainer.decodeIfPresent(Bool.self, forKey: .phoneVerificationRequired)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.availableUserDomains, forKey: .availableUserDomains)
            try container.encodeIfPresent(self.contact, forKey: .contact)
            try container.encode(self.did, forKey: .did)
            try container.encodeIfPresent(self.inviteCodeRequired, forKey: .inviteCodeRequired)
            try container.encodeIfPresent(self.links, forKey: .links)
            try container.encodeIfPresent(self.phoneVerificationRequired, forKey: .phoneVerificationRequired)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerDescribeServer_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerDescribeServer() async throws -> comatprototypes.ServerDescribeServer_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.describeServer", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerDescribeServer_Error(error: error)
        }
    }
}
