//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerCreateInviteCodes_AccountCodes: Codable, Sendable {
        public var account: String
        public var codes: [String]
        public var _unknownValues: [String: AnyCodable]

        public init(account: String, codes: [String]) {
            self.account = account
            self.codes = codes
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case account
            case codes
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.account = try keyedContainer.decode(String.self, forKey: .account)
            self.codes = try keyedContainer.decode([String].self, forKey: .codes)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.account, forKey: .account)
            try container.encode(self.codes, forKey: .codes)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerCreateInviteCodes_Input: Codable, Sendable {
        public var codeCount: Int
        public var forAccounts: [String]?
        public var useCount: Int
        public var _unknownValues: [String: AnyCodable]

        public init(codeCount: Int, forAccounts: [String]? = nil, useCount: Int) {
            self.codeCount = codeCount
            self.forAccounts = forAccounts
            self.useCount = useCount
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case codeCount
            case forAccounts
            case useCount
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.codeCount = try keyedContainer.decode(Int.self, forKey: .codeCount)
            self.forAccounts = try keyedContainer.decodeIfPresent([String].self, forKey: .forAccounts)
            self.useCount = try keyedContainer.decode(Int.self, forKey: .useCount)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.codeCount, forKey: .codeCount)
            try container.encodeIfPresent(self.forAccounts, forKey: .forAccounts)
            try container.encode(self.useCount, forKey: .useCount)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerCreateInviteCodes_Output: Codable, Sendable {
        public var codes: [ServerCreateInviteCodes_AccountCodes]
        public var _unknownValues: [String: AnyCodable]

        public init(codes: [ServerCreateInviteCodes_AccountCodes]) {
            self.codes = codes
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case codes
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.codes = try keyedContainer.decode([ServerCreateInviteCodes_AccountCodes].self, forKey: .codes)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.codes, forKey: .codes)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerCreateInviteCodes_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerCreateInviteCodes(input: comatprototypes.ServerCreateInviteCodes_Input) async throws -> comatprototypes.ServerCreateInviteCodes_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.createInviteCodes", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerCreateInviteCodes_Error(error: error)
        }
    }
}
