//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct TempCheckSignupQueue_Output: Codable, Sendable {
        public var activated: Bool
        public var estimatedTimeMs: Int?
        public var placeInQueue: Int?
        public let _unknownValues: [String: AnyCodable]

        public init(activated: Bool, estimatedTimeMs: Int? = nil, placeInQueue: Int? = nil) {
            self.activated = activated
            self.estimatedTimeMs = estimatedTimeMs
            self.placeInQueue = placeInQueue
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case activated
            case estimatedTimeMs
            case placeInQueue
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.activated = try keyedContainer.decode(Bool.self, forKey: .activated)
            self.estimatedTimeMs = try keyedContainer.decodeIfPresent(Int.self, forKey: .estimatedTimeMs)
            self.placeInQueue = try keyedContainer.decodeIfPresent(Int.self, forKey: .placeInQueue)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.activated, forKey: .activated)
            try container.encodeIfPresent(self.estimatedTimeMs, forKey: .estimatedTimeMs)
            try container.encodeIfPresent(self.placeInQueue, forKey: .placeInQueue)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum TempCheckSignupQueue_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func TempCheckSignupQueue() async throws -> comatprototypes.TempCheckSignupQueue_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.temp.checkSignupQueue", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.TempCheckSignupQueue_Error(error: error)
        }
    }
}
