//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct SyncListReposByCollection_Output: Codable, Sendable {
        public var cursor: String?
        public var repos: [SyncListReposByCollection_Repo]
        public var _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, repos: [SyncListReposByCollection_Repo]) {
            self.cursor = cursor
            self.repos = repos
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case repos
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.repos = try keyedContainer.decode([SyncListReposByCollection_Repo].self, forKey: .repos)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.repos, forKey: .repos)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct SyncListReposByCollection_Repo: Codable, Sendable {
        public var did: String
        public var _unknownValues: [String: AnyCodable]

        public init(did: String) {
            self.did = did
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case did
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.did, forKey: .did)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncListReposByCollection_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func SyncListReposByCollection(collection: String, cursor: String? = nil, limit: Int? = nil) async throws -> comatprototypes.SyncListReposByCollection_Output {
        let params: Parameters = ["collection": .string(collection), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "com.atproto.sync.listReposByCollection", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.SyncListReposByCollection_Error(error: error)
        }
    }
}
