//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerConfirmEmail_Input: Codable, Sendable {
        public var email: String
        public var token: String
        public var _unknownValues: [String: AnyCodable]

        public init(email: String, token: String) {
            self.email = email
            self.token = token
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case email
            case token
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.email = try keyedContainer.decode(String.self, forKey: .email)
            self.token = try keyedContainer.decode(String.self, forKey: .token)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.email, forKey: .email)
            try container.encode(self.token, forKey: .token)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerConfirmEmail_Error: XRPCError {
        case accountnotfound(String?)
        case expiredtoken(String?)
        case invalidemail(String?)
        case invalidtoken(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "AccountNotFound":
                self = .accountnotfound(error.message)
            case "ExpiredToken":
                self = .expiredtoken(error.message)
            case "InvalidToken":
                self = .invalidtoken(error.message)
            case "InvalidEmail":
                self = .invalidemail(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .accountnotfound:
                return "AccountNotFound"
            case .expiredtoken:
                return "ExpiredToken"
            case .invalidtoken:
                return "InvalidToken"
            case .invalidemail:
                return "InvalidEmail"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .accountnotfound(message):
                return message
            case let .expiredtoken(message):
                return message
            case let .invalidtoken(message):
                return message
            case let .invalidemail(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerConfirmEmail(input: comatprototypes.ServerConfirmEmail_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.confirmEmail", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerConfirmEmail_Error(error: error)
        }
    }
}
