//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerCheckAccountStatus_Output: Codable, Sendable {
        public var activated: Bool
        public var expectedBlobs: Int
        public var importedBlobs: Int
        public var indexedRecords: Int
        public var privateStateValues: Int
        public var repoBlocks: Int
        public var repoCommit: String
        public var repoRev: String
        public var validDid: Bool
        public let _unknownValues: [String: AnyCodable]

        public init(activated: Bool, expectedBlobs: Int, importedBlobs: Int, indexedRecords: Int, privateStateValues: Int, repoBlocks: Int, repoCommit: String, repoRev: String, validDid: Bool) {
            self.activated = activated
            self.expectedBlobs = expectedBlobs
            self.importedBlobs = importedBlobs
            self.indexedRecords = indexedRecords
            self.privateStateValues = privateStateValues
            self.repoBlocks = repoBlocks
            self.repoCommit = repoCommit
            self.repoRev = repoRev
            self.validDid = validDid
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case activated
            case expectedBlobs
            case importedBlobs
            case indexedRecords
            case privateStateValues
            case repoBlocks
            case repoCommit
            case repoRev
            case validDid
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.activated = try keyedContainer.decode(Bool.self, forKey: .activated)
            self.expectedBlobs = try keyedContainer.decode(Int.self, forKey: .expectedBlobs)
            self.importedBlobs = try keyedContainer.decode(Int.self, forKey: .importedBlobs)
            self.indexedRecords = try keyedContainer.decode(Int.self, forKey: .indexedRecords)
            self.privateStateValues = try keyedContainer.decode(Int.self, forKey: .privateStateValues)
            self.repoBlocks = try keyedContainer.decode(Int.self, forKey: .repoBlocks)
            self.repoCommit = try keyedContainer.decode(String.self, forKey: .repoCommit)
            self.repoRev = try keyedContainer.decode(String.self, forKey: .repoRev)
            self.validDid = try keyedContainer.decode(Bool.self, forKey: .validDid)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.activated, forKey: .activated)
            try container.encode(self.expectedBlobs, forKey: .expectedBlobs)
            try container.encode(self.importedBlobs, forKey: .importedBlobs)
            try container.encode(self.indexedRecords, forKey: .indexedRecords)
            try container.encode(self.privateStateValues, forKey: .privateStateValues)
            try container.encode(self.repoBlocks, forKey: .repoBlocks)
            try container.encode(self.repoCommit, forKey: .repoCommit)
            try container.encode(self.repoRev, forKey: .repoRev)
            try container.encode(self.validDid, forKey: .validDid)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerCheckAccountStatus_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerCheckAccountStatus() async throws -> comatprototypes.ServerCheckAccountStatus_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.checkAccountStatus", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerCheckAccountStatus_Error(error: error)
        }
    }
}
