//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct SyncGetHead_Output: Codable, Sendable {
        public var root: String
        public let _unknownValues: [String: AnyCodable]

        public init(root: String) {
            self.root = root
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case root
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.root = try keyedContainer.decode(String.self, forKey: .root)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.root, forKey: .root)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncGetHead_Error: XRPCError {
        case headnotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "HeadNotFound":
                self = .headnotfound(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .headnotfound:
                return "HeadNotFound"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .headnotfound(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func SyncGetHead(did: String) async throws -> comatprototypes.SyncGetHead_Output {
        let params: Parameters = ["did": .string(did)]
        do {
            return try await fetch(endpoint: "com.atproto.sync.getHead", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.SyncGetHead_Error(error: error)
        }
    }
}
