//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoListMissingBlobs_Output: Codable, Sendable {
        public var blobs: [RepoListMissingBlobs_RecordBlob]
        public var cursor: String?
        public var _unknownValues: [String: AnyCodable]

        public init(blobs: [RepoListMissingBlobs_RecordBlob], cursor: String? = nil) {
            self.blobs = blobs
            self.cursor = cursor
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case blobs
            case cursor
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.blobs = try keyedContainer.decode([RepoListMissingBlobs_RecordBlob].self, forKey: .blobs)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.blobs, forKey: .blobs)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoListMissingBlobs_RecordBlob: Codable, Sendable {
        public var cid: String
        public var recordUri: String
        public var _unknownValues: [String: AnyCodable]

        public init(cid: String, recordUri: String) {
            self.cid = cid
            self.recordUri = recordUri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case recordUri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.recordUri = try keyedContainer.decode(String.self, forKey: .recordUri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.recordUri, forKey: .recordUri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoListMissingBlobs_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoListMissingBlobs(cursor: String? = nil, limit: Int? = nil) async throws -> comatprototypes.RepoListMissingBlobs_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "com.atproto.repo.listMissingBlobs", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoListMissingBlobs_Error(error: error)
        }
    }
}
