//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerGetSession_Output: Codable, Sendable {
        public var active: Bool?
        public var did: String
        public var didDoc: LexiconTypeDecoder?
        public var email: String?
        public var emailAuthFactor: Bool?
        public var emailConfirmed: Bool?
        public var handle: String
        public var status: ServerGetSession_Output_Status?
        public var _unknownValues: [String: AnyCodable]

        public init(active: Bool? = nil, did: String, didDoc: LexiconTypeDecoder? = nil, email: String? = nil, emailAuthFactor: Bool? = nil, emailConfirmed: Bool? = nil, handle: String, status: ServerGetSession_Output_Status? = nil) {
            self.active = active
            self.did = did
            self.didDoc = didDoc
            self.email = email
            self.emailAuthFactor = emailAuthFactor
            self.emailConfirmed = emailConfirmed
            self.handle = handle
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case active
            case did
            case didDoc
            case email
            case emailAuthFactor
            case emailConfirmed
            case handle
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.active = try keyedContainer.decodeIfPresent(Bool.self, forKey: .active)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.didDoc = try keyedContainer.decodeIfPresent(LexiconTypeDecoder.self, forKey: .didDoc)
            self.email = try keyedContainer.decodeIfPresent(String.self, forKey: .email)
            self.emailAuthFactor = try keyedContainer.decodeIfPresent(Bool.self, forKey: .emailAuthFactor)
            self.emailConfirmed = try keyedContainer.decodeIfPresent(Bool.self, forKey: .emailConfirmed)
            self.handle = try keyedContainer.decode(String.self, forKey: .handle)
            self.status = try keyedContainer.decodeIfPresent(ServerGetSession_Output_Status.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.active, forKey: .active)
            try container.encode(self.did, forKey: .did)
            try container.encodeIfPresent(self.didDoc, forKey: .didDoc)
            try container.encodeIfPresent(self.email, forKey: .email)
            try container.encodeIfPresent(self.emailAuthFactor, forKey: .emailAuthFactor)
            try container.encodeIfPresent(self.emailConfirmed, forKey: .emailConfirmed)
            try container.encode(self.handle, forKey: .handle)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerGetSession_Output_Status: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case takendown
        case suspended
        case deactivated
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum ServerGetSession_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerGetSession() async throws -> comatprototypes.ServerGetSession_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.getSession", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerGetSession_Error(error: error)
        }
    }
}
