//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public indirect enum IdentityResolveIdentity_Error: XRPCError {
        case diddeactivated(String?)
        case didnotfound(String?)
        case handlenotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "HandleNotFound":
                self = .handlenotfound(error.message)
            case "DidNotFound":
                self = .didnotfound(error.message)
            case "DidDeactivated":
                self = .diddeactivated(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .handlenotfound:
                return "HandleNotFound"
            case .didnotfound:
                return "DidNotFound"
            case .diddeactivated:
                return "DidDeactivated"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .handlenotfound(message):
                return message
            case let .didnotfound(message):
                return message
            case let .diddeactivated(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func IdentityResolveIdentity(identifier: String) async throws -> comatprototypes.IdentityDefs_IdentityInfo {
        let params: Parameters = ["identifier": .string(identifier)]
        do {
            return try await fetch(endpoint: "com.atproto.identity.resolveIdentity", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.IdentityResolveIdentity_Error(error: error)
        }
    }
}
