//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoDescribeRepo_Output: Codable, Sendable {
        public var collections: [String]
        public var did: String
        public var didDoc: UnknownATPValue
        public var handle: String
        public var handleIsCorrect: Bool
        public let _unknownValues: [String: AnyCodable]

        public init(collections: [String], did: String, didDoc: UnknownATPValue, handle: String, handleIsCorrect: Bool) {
            self.collections = collections
            self.did = did
            self.didDoc = didDoc
            self.handle = handle
            self.handleIsCorrect = handleIsCorrect
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case collections
            case did
            case didDoc
            case handle
            case handleIsCorrect
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.collections = try keyedContainer.decode([String].self, forKey: .collections)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.didDoc = try keyedContainer.decode(UnknownATPValue.self, forKey: .didDoc)
            self.handle = try keyedContainer.decode(String.self, forKey: .handle)
            self.handleIsCorrect = try keyedContainer.decode(Bool.self, forKey: .handleIsCorrect)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.collections, forKey: .collections)
            try container.encode(self.did, forKey: .did)
            try container.encode(self.didDoc, forKey: .didDoc)
            try container.encode(self.handle, forKey: .handle)
            try container.encode(self.handleIsCorrect, forKey: .handleIsCorrect)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoDescribeRepo_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoDescribeRepo(repo: String) async throws -> comatprototypes.RepoDescribeRepo_Output {
        let params: Parameters = ["repo": .string(repo)]
        do {
            return try await fetch(endpoint: "com.atproto.repo.describeRepo", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoDescribeRepo_Error(error: error)
        }
    }
}
