//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct IdentityResolveDid_Output: Codable, Sendable {
        public var didDoc: UnknownATPValue
        public let _unknownValues: [String: AnyCodable]

        public init(didDoc: UnknownATPValue) {
            self.didDoc = didDoc
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case didDoc
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.didDoc = try keyedContainer.decode(UnknownATPValue.self, forKey: .didDoc)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.didDoc, forKey: .didDoc)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum IdentityResolveDid_Error: XRPCError {
        case diddeactivated(String?)
        case didnotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "DidNotFound":
                self = .didnotfound(error.message)
            case "DidDeactivated":
                self = .diddeactivated(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .didnotfound:
                return "DidNotFound"
            case .diddeactivated:
                return "DidDeactivated"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .didnotfound(message):
                return message
            case let .diddeactivated(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func IdentityResolveDid(did: String) async throws -> comatprototypes.IdentityResolveDid_Output {
        let params: Parameters = ["did": .string(did)]
        do {
            return try await fetch(endpoint: "com.atproto.identity.resolveDid", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.IdentityResolveDid_Error(error: error)
        }
    }
}
