//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerGetServiceAuth_Output: Codable, Sendable {
        public var token: String
        public let _unknownValues: [String: AnyCodable]

        public init(token: String) {
            self.token = token
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case token
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.token = try keyedContainer.decode(String.self, forKey: .token)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.token, forKey: .token)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerGetServiceAuth_Error: XRPCError {
        case badexpiration(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "BadExpiration":
                self = .badexpiration(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .badexpiration:
                return "BadExpiration"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .badexpiration(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerGetServiceAuth(aud: String, exp: Int? = nil, lxm: String? = nil) async throws -> comatprototypes.ServerGetServiceAuth_Output {
        let params: Parameters = ["aud": .string(aud), "exp": .integer(exp), "lxm": .string(lxm)]
        do {
            return try await fetch(endpoint: "com.atproto.server.getServiceAuth", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerGetServiceAuth_Error(error: error)
        }
    }
}
