//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct SyncGetHostStatus_Output: Codable, Sendable {
        public var accountCount: Int?
        public var hostname: String
        public var seq: Int?
        public var status: SyncDefs_HostStatus?
        public var _unknownValues: [String: AnyCodable]

        public init(accountCount: Int? = nil, hostname: String, seq: Int? = nil, status: SyncDefs_HostStatus? = nil) {
            self.accountCount = accountCount
            self.hostname = hostname
            self.seq = seq
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case accountCount
            case hostname
            case seq
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.accountCount = try keyedContainer.decodeIfPresent(Int.self, forKey: .accountCount)
            self.hostname = try keyedContainer.decode(String.self, forKey: .hostname)
            self.seq = try keyedContainer.decodeIfPresent(Int.self, forKey: .seq)
            self.status = try keyedContainer.decodeIfPresent(SyncDefs_HostStatus.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.accountCount, forKey: .accountCount)
            try container.encode(self.hostname, forKey: .hostname)
            try container.encodeIfPresent(self.seq, forKey: .seq)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncGetHostStatus_Error: XRPCError {
        case hostnotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "HostNotFound":
                self = .hostnotfound(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .hostnotfound:
                return "HostNotFound"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .hostnotfound(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func SyncGetHostStatus(hostname: String) async throws -> comatprototypes.SyncGetHostStatus_Output {
        let params: Parameters = ["hostname": .string(hostname)]
        do {
            return try await fetch(endpoint: "com.atproto.sync.getHostStatus", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.SyncGetHostStatus_Error(error: error)
        }
    }
}
