//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct IdentityRefreshIdentity_Input: Codable, Sendable {
        public var identifier: String
        public var _unknownValues: [String: AnyCodable]

        public init(identifier: String) {
            self.identifier = identifier
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case identifier
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.identifier = try keyedContainer.decode(String.self, forKey: .identifier)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.identifier, forKey: .identifier)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum IdentityRefreshIdentity_Error: XRPCError {
        case diddeactivated(String?)
        case didnotfound(String?)
        case handlenotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "HandleNotFound":
                self = .handlenotfound(error.message)
            case "DidNotFound":
                self = .didnotfound(error.message)
            case "DidDeactivated":
                self = .diddeactivated(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .handlenotfound:
                return "HandleNotFound"
            case .didnotfound:
                return "DidNotFound"
            case .diddeactivated:
                return "DidDeactivated"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .handlenotfound(message):
                return message
            case let .didnotfound(message):
                return message
            case let .diddeactivated(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func IdentityRefreshIdentity(input: comatprototypes.IdentityRefreshIdentity_Input) async throws -> comatprototypes.IdentityDefs_IdentityInfo {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.identity.refreshIdentity", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.IdentityRefreshIdentity_Error(error: error)
        }
    }
}
