//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct AdminSearchAccounts_Output: Codable, Sendable {
        public var accounts: [AdminDefs_AccountView]
        public var cursor: String?
        public var _unknownValues: [String: AnyCodable]

        public init(accounts: [AdminDefs_AccountView], cursor: String? = nil) {
            self.accounts = accounts
            self.cursor = cursor
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case accounts
            case cursor
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.accounts = try keyedContainer.decode([AdminDefs_AccountView].self, forKey: .accounts)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.accounts, forKey: .accounts)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminSearchAccounts_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func AdminSearchAccounts(cursor: String? = nil, email: String? = nil, limit: Int? = nil) async throws -> comatprototypes.AdminSearchAccounts_Output {
        let params: Parameters = ["cursor": .string(cursor), "email": .string(email), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "com.atproto.admin.searchAccounts", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.AdminSearchAccounts_Error(error: error)
        }
    }
}
