//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct SyncListBlobs_Output: Codable, Sendable {
        public var cids: [String]
        public var cursor: String?
        public var _unknownValues: [String: AnyCodable]

        public init(cids: [String], cursor: String? = nil) {
            self.cids = cids
            self.cursor = cursor
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cids
            case cursor
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cids = try keyedContainer.decode([String].self, forKey: .cids)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cids, forKey: .cids)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncListBlobs_Error: XRPCError {
        case repodeactivated(String?)
        case reponotfound(String?)
        case reposuspended(String?)
        case repotakendown(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "RepoNotFound":
                self = .reponotfound(error.message)
            case "RepoTakendown":
                self = .repotakendown(error.message)
            case "RepoSuspended":
                self = .reposuspended(error.message)
            case "RepoDeactivated":
                self = .repodeactivated(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .reponotfound:
                return "RepoNotFound"
            case .repotakendown:
                return "RepoTakendown"
            case .reposuspended:
                return "RepoSuspended"
            case .repodeactivated:
                return "RepoDeactivated"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .reponotfound(message):
                return message
            case let .repotakendown(message):
                return message
            case let .reposuspended(message):
                return message
            case let .repodeactivated(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func SyncListBlobs(cursor: String? = nil, did: String, limit: Int? = nil, since: String? = nil) async throws -> comatprototypes.SyncListBlobs_Output {
        let params: Parameters = ["cursor": .string(cursor), "did": .string(did), "limit": .integer(limit), "since": .string(since)]
        do {
            return try await fetch(endpoint: "com.atproto.sync.listBlobs", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.SyncListBlobs_Error(error: error)
        }
    }
}
