//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerCreateSession_Input: Codable, Sendable {
        public var allowTakendown: Bool?
        public var authFactorToken: String?
        public var identifier: String
        public var password: String
        public let _unknownValues: [String: AnyCodable]

        public init(allowTakendown: Bool? = nil, authFactorToken: String? = nil, identifier: String, password: String) {
            self.allowTakendown = allowTakendown
            self.authFactorToken = authFactorToken
            self.identifier = identifier
            self.password = password
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case allowTakendown
            case authFactorToken
            case identifier
            case password
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.allowTakendown = try keyedContainer.decodeIfPresent(Bool.self, forKey: .allowTakendown)
            self.authFactorToken = try keyedContainer.decodeIfPresent(String.self, forKey: .authFactorToken)
            self.identifier = try keyedContainer.decode(String.self, forKey: .identifier)
            self.password = try keyedContainer.decode(String.self, forKey: .password)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.allowTakendown, forKey: .allowTakendown)
            try container.encodeIfPresent(self.authFactorToken, forKey: .authFactorToken)
            try container.encode(self.identifier, forKey: .identifier)
            try container.encode(self.password, forKey: .password)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerCreateSession_Output: Codable, Sendable {
        public var accessJwt: String
        public var active: Bool?
        public var did: String
        public var didDoc: UnknownATPValue?
        public var email: String?
        public var emailAuthFactor: Bool?
        public var emailConfirmed: Bool?
        public var handle: String
        public var refreshJwt: String
        public var status: ServerCreateSession_Output_Status?
        public let _unknownValues: [String: AnyCodable]

        public init(accessJwt: String, active: Bool? = nil, did: String, didDoc: UnknownATPValue? = nil, email: String? = nil, emailAuthFactor: Bool? = nil, emailConfirmed: Bool? = nil, handle: String, refreshJwt: String, status: ServerCreateSession_Output_Status? = nil) {
            self.accessJwt = accessJwt
            self.active = active
            self.did = did
            self.didDoc = didDoc
            self.email = email
            self.emailAuthFactor = emailAuthFactor
            self.emailConfirmed = emailConfirmed
            self.handle = handle
            self.refreshJwt = refreshJwt
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case accessJwt
            case active
            case did
            case didDoc
            case email
            case emailAuthFactor
            case emailConfirmed
            case handle
            case refreshJwt
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.accessJwt = try keyedContainer.decode(String.self, forKey: .accessJwt)
            self.active = try keyedContainer.decodeIfPresent(Bool.self, forKey: .active)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.didDoc = try keyedContainer.decodeIfPresent(UnknownATPValue.self, forKey: .didDoc)
            self.email = try keyedContainer.decodeIfPresent(String.self, forKey: .email)
            self.emailAuthFactor = try keyedContainer.decodeIfPresent(Bool.self, forKey: .emailAuthFactor)
            self.emailConfirmed = try keyedContainer.decodeIfPresent(Bool.self, forKey: .emailConfirmed)
            self.handle = try keyedContainer.decode(String.self, forKey: .handle)
            self.refreshJwt = try keyedContainer.decode(String.self, forKey: .refreshJwt)
            self.status = try keyedContainer.decodeIfPresent(ServerCreateSession_Output_Status.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.accessJwt, forKey: .accessJwt)
            try container.encodeIfPresent(self.active, forKey: .active)
            try container.encode(self.did, forKey: .did)
            try container.encodeIfPresent(self.didDoc, forKey: .didDoc)
            try container.encodeIfPresent(self.email, forKey: .email)
            try container.encodeIfPresent(self.emailAuthFactor, forKey: .emailAuthFactor)
            try container.encodeIfPresent(self.emailConfirmed, forKey: .emailConfirmed)
            try container.encode(self.handle, forKey: .handle)
            try container.encode(self.refreshJwt, forKey: .refreshJwt)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerCreateSession_Output_Status: RawRepresentable, Codable, Sendable {
        case takendown
        case suspended
        case deactivated
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum ServerCreateSession_Error: XRPCError {
        case accounttakedown(String?)
        case authfactortokenrequired(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "AccountTakedown":
                self = .accounttakedown(error.message)
            case "AuthFactorTokenRequired":
                self = .authfactortokenrequired(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .accounttakedown:
                return "AccountTakedown"
            case .authfactortokenrequired:
                return "AuthFactorTokenRequired"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .accounttakedown(message):
                return message
            case let .authfactortokenrequired(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerCreateSession(input: comatprototypes.ServerCreateSession_Input) async throws -> comatprototypes.ServerCreateSession_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.createSession", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerCreateSession_Error(error: error)
        }
    }
}
