//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoListRecords_Output: Codable, Sendable {
        public var cursor: String?
        public var records: [RepoListRecords_Record]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, records: [RepoListRecords_Record]) {
            self.cursor = cursor
            self.records = records
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case records
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.records = try keyedContainer.decode([RepoListRecords_Record].self, forKey: .records)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.records, forKey: .records)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoListRecords_Record: Codable, Sendable {
        public var cid: String
        public var uri: String
        public var value: UnknownATPValue
        public let _unknownValues: [String: AnyCodable]

        public init(cid: String, uri: String, value: UnknownATPValue) {
            self.cid = cid
            self.uri = uri
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case uri
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.value = try keyedContainer.decode(UnknownATPValue.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.uri, forKey: .uri)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoListRecords_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoListRecords(collection: String, cursor: String? = nil, limit: Int? = nil, repo: String, reverse: Bool? = nil) async throws -> comatprototypes.RepoListRecords_Output {
        let params: Parameters = ["collection": .string(collection), "cursor": .string(cursor), "limit": .integer(limit), "repo": .string(repo), "reverse": .bool(reverse)]
        do {
            return try await fetch(endpoint: "com.atproto.repo.listRecords", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoListRecords_Error(error: error)
        }
    }
}
