//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct AdminGetInviteCodes_Output: Codable, Sendable {
        public var codes: [ServerDefs_InviteCode]
        public var cursor: String?
        public var _unknownValues: [String: AnyCodable]

        public init(codes: [ServerDefs_InviteCode], cursor: String? = nil) {
            self.codes = codes
            self.cursor = cursor
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case codes
            case cursor
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.codes = try keyedContainer.decode([ServerDefs_InviteCode].self, forKey: .codes)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.codes, forKey: .codes)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminGetInviteCodes_Sort: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case recent
        case usage
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "recent":
                self = .recent
            case "usage":
                self = .usage
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .recent:
                "recent"
            case .usage:
                "usage"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum AdminGetInviteCodes_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func AdminGetInviteCodes(cursor: String? = nil, limit: Int? = nil, sort: comatprototypes.AdminGetInviteCodes_Sort? = nil) async throws -> comatprototypes.AdminGetInviteCodes_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "sort": .string(sort?.rawValue)]
        do {
            return try await fetch(endpoint: "com.atproto.admin.getInviteCodes", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.AdminGetInviteCodes_Error(error: error)
        }
    }
}
