//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct AdminDisableInviteCodes_Input: Codable, Sendable {
        public var accounts: [String]?
        public var codes: [String]?
        public let _unknownValues: [String: AnyCodable]

        public init(accounts: [String]? = nil, codes: [String]? = nil) {
            self.accounts = accounts
            self.codes = codes
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case accounts
            case codes
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.accounts = try keyedContainer.decodeIfPresent([String].self, forKey: .accounts)
            self.codes = try keyedContainer.decodeIfPresent([String].self, forKey: .codes)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.accounts, forKey: .accounts)
            try container.encodeIfPresent(self.codes, forKey: .codes)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminDisableInviteCodes_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func AdminDisableInviteCodes(input: comatprototypes.AdminDisableInviteCodes_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.admin.disableInviteCodes", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.AdminDisableInviteCodes_Error(error: error)
        }
    }
}
