//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerReserveSigningKey_Input: Codable, Sendable {
        public var did: String?
        public let _unknownValues: [String: AnyCodable]

        public init(did: String? = nil) {
            self.did = did
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case did
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.did = try keyedContainer.decodeIfPresent(String.self, forKey: .did)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.did, forKey: .did)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerReserveSigningKey_Output: Codable, Sendable {
        public var signingKey: String
        public let _unknownValues: [String: AnyCodable]

        public init(signingKey: String) {
            self.signingKey = signingKey
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case signingKey
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.signingKey = try keyedContainer.decode(String.self, forKey: .signingKey)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.signingKey, forKey: .signingKey)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerReserveSigningKey_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerReserveSigningKey(input: comatprototypes.ServerReserveSigningKey_Input) async throws -> comatprototypes.ServerReserveSigningKey_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.reserveSigningKey", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerReserveSigningKey_Error(error: error)
        }
    }
}
