//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct AdminGetAccountInfos_Output: Codable, Sendable {
        public var infos: [AdminDefs_AccountView]
        public let _unknownValues: [String: AnyCodable]

        public init(infos: [AdminDefs_AccountView]) {
            self.infos = infos
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case infos
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.infos = try keyedContainer.decode([AdminDefs_AccountView].self, forKey: .infos)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.infos, forKey: .infos)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminGetAccountInfos_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func AdminGetAccountInfos(dids: [String]) async throws -> comatprototypes.AdminGetAccountInfos_Output {
        let params: Parameters = ["dids": .array(dids)]
        do {
            return try await fetch(endpoint: "com.atproto.admin.getAccountInfos", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.AdminGetAccountInfos_Error(error: error)
        }
    }
}
