//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ModerationCreateReport_Input: Codable, Sendable {
        public var modTool: ModerationCreateReport_ModTool?
        public var reason: String?
        public var reasonType: ModerationDefs_ReasonType
        public var subject: ModerationCreateReport_Input_Subject
        public let _unknownValues: [String: AnyCodable]

        public init(modTool: ModerationCreateReport_ModTool? = nil, reason: String? = nil, reasonType: ModerationDefs_ReasonType, subject: ModerationCreateReport_Input_Subject) {
            self.modTool = modTool
            self.reason = reason
            self.reasonType = reasonType
            self.subject = subject
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case modTool
            case reason
            case reasonType
            case subject
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.modTool = try keyedContainer.decodeIfPresent(ModerationCreateReport_ModTool.self, forKey: .modTool)
            self.reason = try keyedContainer.decodeIfPresent(String.self, forKey: .reason)
            self.reasonType = try keyedContainer.decode(ModerationDefs_ReasonType.self, forKey: .reasonType)
            self.subject = try keyedContainer.decode(ModerationCreateReport_Input_Subject.self, forKey: .subject)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.modTool, forKey: .modTool)
            try container.encodeIfPresent(self.reason, forKey: .reason)
            try container.encode(self.reasonType, forKey: .reasonType)
            try container.encode(self.subject, forKey: .subject)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ModerationCreateReport_Input_Subject: Codable, Sendable {
        case adminDefsRepoRef(AdminDefs_RepoRef)
        case repoStrongRef(RepoStrongRef)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.admin.defs#repoRef":
                self = try .adminDefsRepoRef(.init(from: decoder))
            case "com.atproto.repo.strongRef":
                self = try .repoStrongRef(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .adminDefsRepoRef(value):
                try container.encode("com.atproto.admin.defs#repoRef", forKey: .type)
                try value.encode(to: encoder)
            case let .repoStrongRef(value):
                try container.encode("com.atproto.repo.strongRef", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public struct ModerationCreateReport_ModTool: Codable, Sendable {
        public var meta: UnknownATPValue?
        public var name: String
        public let _unknownValues: [String: AnyCodable]

        public init(meta: UnknownATPValue? = nil, name: String) {
            self.meta = meta
            self.name = name
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case meta
            case name
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.meta = try keyedContainer.decodeIfPresent(UnknownATPValue.self, forKey: .meta)
            self.name = try keyedContainer.decode(String.self, forKey: .name)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.meta, forKey: .meta)
            try container.encode(self.name, forKey: .name)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ModerationCreateReport_Output: Codable, Sendable {
        public var createdAt: String
        public var id: Int
        public var reason: String?
        public var reasonType: ModerationDefs_ReasonType
        public var reportedBy: String
        public var subject: ModerationCreateReport_Output_Subject
        public let _unknownValues: [String: AnyCodable]

        public init(createdAt: String, id: Int, reason: String? = nil, reasonType: ModerationDefs_ReasonType, reportedBy: String, subject: ModerationCreateReport_Output_Subject) {
            self.createdAt = createdAt
            self.id = id
            self.reason = reason
            self.reasonType = reasonType
            self.reportedBy = reportedBy
            self.subject = subject
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case createdAt
            case id
            case reason
            case reasonType
            case reportedBy
            case subject
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
            self.id = try keyedContainer.decode(Int.self, forKey: .id)
            self.reason = try keyedContainer.decodeIfPresent(String.self, forKey: .reason)
            self.reasonType = try keyedContainer.decode(ModerationDefs_ReasonType.self, forKey: .reasonType)
            self.reportedBy = try keyedContainer.decode(String.self, forKey: .reportedBy)
            self.subject = try keyedContainer.decode(ModerationCreateReport_Output_Subject.self, forKey: .subject)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.id, forKey: .id)
            try container.encodeIfPresent(self.reason, forKey: .reason)
            try container.encode(self.reasonType, forKey: .reasonType)
            try container.encode(self.reportedBy, forKey: .reportedBy)
            try container.encode(self.subject, forKey: .subject)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ModerationCreateReport_Output_Subject: Codable, Sendable {
        case adminDefsRepoRef(AdminDefs_RepoRef)
        case repoStrongRef(RepoStrongRef)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.admin.defs#repoRef":
                self = try .adminDefsRepoRef(.init(from: decoder))
            case "com.atproto.repo.strongRef":
                self = try .repoStrongRef(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .adminDefsRepoRef(value):
                try container.encode("com.atproto.admin.defs#repoRef", forKey: .type)
                try value.encode(to: encoder)
            case let .repoStrongRef(value):
                try container.encode("com.atproto.repo.strongRef", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public indirect enum ModerationCreateReport_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ModerationCreateReport(input: comatprototypes.ModerationCreateReport_Input) async throws -> comatprototypes.ModerationCreateReport_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.moderation.createReport", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ModerationCreateReport_Error(error: error)
        }
    }
}
