//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct IdentityGetRecommendedDidCredentials_Output: Codable, Sendable {
        public var alsoKnownAs: [String]?
        public var rotationKeys: [String]?
        public var services: LexiconTypeDecoder?
        public var verificationMethods: LexiconTypeDecoder?
        public var _unknownValues: [String: AnyCodable]

        public init(alsoKnownAs: [String]? = nil, rotationKeys: [String]? = nil, services: LexiconTypeDecoder? = nil, verificationMethods: LexiconTypeDecoder? = nil) {
            self.alsoKnownAs = alsoKnownAs
            self.rotationKeys = rotationKeys
            self.services = services
            self.verificationMethods = verificationMethods
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case alsoKnownAs
            case rotationKeys
            case services
            case verificationMethods
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.alsoKnownAs = try keyedContainer.decodeIfPresent([String].self, forKey: .alsoKnownAs)
            self.rotationKeys = try keyedContainer.decodeIfPresent([String].self, forKey: .rotationKeys)
            self.services = try keyedContainer.decodeIfPresent(LexiconTypeDecoder.self, forKey: .services)
            self.verificationMethods = try keyedContainer.decodeIfPresent(LexiconTypeDecoder.self, forKey: .verificationMethods)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.alsoKnownAs, forKey: .alsoKnownAs)
            try container.encodeIfPresent(self.rotationKeys, forKey: .rotationKeys)
            try container.encodeIfPresent(self.services, forKey: .services)
            try container.encodeIfPresent(self.verificationMethods, forKey: .verificationMethods)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum IdentityGetRecommendedDidCredentials_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func IdentityGetRecommendedDidCredentials() async throws -> comatprototypes.IdentityGetRecommendedDidCredentials_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.identity.getRecommendedDidCredentials", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.IdentityGetRecommendedDidCredentials_Error(error: error)
        }
    }
}
