//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct RepoUploadBlob_Output: Codable, Sendable {
        public var blob: LexBlob
        public let _unknownValues: [String: AnyCodable]

        public init(blob: LexBlob) {
            self.blob = blob
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case blob
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.blob = try keyedContainer.decode(LexBlob.self, forKey: .blob)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.blob, forKey: .blob)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoUploadBlob_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func RepoUploadBlob(input: Data) async throws -> comatprototypes.RepoUploadBlob_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.repo.uploadBlob", contentType: "*/*", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.RepoUploadBlob_Error(error: error)
        }
    }
}
