//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public struct ServerCreateAppPassword_AppPassword: Codable, Sendable {
        public var createdAt: String
        public var name: String
        public var password: String
        public var privileged: Bool?
        public let _unknownValues: [String: AnyCodable]

        public init(createdAt: String, name: String, password: String, privileged: Bool? = nil) {
            self.createdAt = createdAt
            self.name = name
            self.password = password
            self.privileged = privileged
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case createdAt
            case name
            case password
            case privileged
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
            self.name = try keyedContainer.decode(String.self, forKey: .name)
            self.password = try keyedContainer.decode(String.self, forKey: .password)
            self.privileged = try keyedContainer.decodeIfPresent(Bool.self, forKey: .privileged)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.name, forKey: .name)
            try container.encode(self.password, forKey: .password)
            try container.encodeIfPresent(self.privileged, forKey: .privileged)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerCreateAppPassword_Input: Codable, Sendable {
        public var name: String
        public var privileged: Bool?
        public let _unknownValues: [String: AnyCodable]

        public init(name: String, privileged: Bool? = nil) {
            self.name = name
            self.privileged = privileged
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case name
            case privileged
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.name = try keyedContainer.decode(String.self, forKey: .name)
            self.privileged = try keyedContainer.decodeIfPresent(Bool.self, forKey: .privileged)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.name, forKey: .name)
            try container.encodeIfPresent(self.privileged, forKey: .privileged)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerCreateAppPassword_Error: XRPCError {
        case accounttakedown(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "AccountTakedown":
                self = .accounttakedown(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .accounttakedown:
                return "AccountTakedown"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .accounttakedown(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ServerCreateAppPassword(input: comatprototypes.ServerCreateAppPassword_Input) async throws -> comatprototypes.ServerCreateAppPassword_AppPassword {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "com.atproto.server.createAppPassword", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw comatprototypes.ServerCreateAppPassword_Error(error: error)
        }
    }
}
