//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphStarterpack_FeedItem: Codable, Sendable {
        public var uri: String
        public var _unknownValues: [String: AnyCodable]

        public init(uri: String) {
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }
}

public final class appbskytypes_GraphStarterpack: Codable, Sendable {
    public let type = "app.bsky.graph.starterpack"
    public let createdAt: String
    public let description: String?
    public let descriptionFacets: [appbskytypes.RichtextFacet]?
    public let feeds: [appbskytypes.GraphStarterpack_FeedItem]?
    public let list: String
    public let name: String
    public let _unknownValues: [String: AnyCodable]

    public init(createdAt: String, description: String? = nil, descriptionFacets: [appbskytypes.RichtextFacet]? = nil, feeds: [appbskytypes.GraphStarterpack_FeedItem]? = nil, list: String, name: String) {
        self.createdAt = createdAt
        self.description = description
        self.descriptionFacets = descriptionFacets
        self.feeds = feeds
        self.list = list
        self.name = name
        self._unknownValues = [:]
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case createdAt
        case description
        case descriptionFacets
        case feeds
        case list
        case name
    }

    required public init(from decoder: any Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
        self.description = try keyedContainer.decodeIfPresent(String.self, forKey: .description)
        self.descriptionFacets = try keyedContainer.decodeIfPresent([appbskytypes.RichtextFacet].self, forKey: .descriptionFacets)
        self.feeds = try keyedContainer.decodeIfPresent([appbskytypes.GraphStarterpack_FeedItem].self, forKey: .feeds)
        self.list = try keyedContainer.decode(String.self, forKey: .list)
        self.name = try keyedContainer.decode(String.self, forKey: .name)
        let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
        var _unknownValues = [String: AnyCodable]()
        for key in unknownContainer.allKeys {
            guard CodingKeys(rawValue: key.stringValue) == nil else {
                continue
            }
            _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
        }
        self._unknownValues = _unknownValues
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encodeIfPresent(self.descriptionFacets, forKey: .descriptionFacets)
        try container.encodeIfPresent(self.feeds, forKey: .feeds)
        try container.encode(self.list, forKey: .list)
        try container.encode(self.name, forKey: .name)
        try _unknownValues.encode(to: encoder)
    }
}
