//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct LabelerGetServices_Output: Codable, Sendable {
        public var views: [LabelerGetServices_Output_Views_Elem]
        public var _unknownValues: [String: AnyCodable]

        public init(views: [LabelerGetServices_Output_Views_Elem]) {
            self.views = views
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case views
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.views = try keyedContainer.decode([LabelerGetServices_Output_Views_Elem].self, forKey: .views)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.views, forKey: .views)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum LabelerGetServices_Output_Views_Elem: Codable, Sendable {
        case labelerDefsLabelerView(LabelerDefs_LabelerView)
        case labelerDefsLabelerViewDetailed(LabelerDefs_LabelerViewDetailed)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.labeler.defs#labelerView":
                self = try .labelerDefsLabelerView(.init(from: decoder))
            case "app.bsky.labeler.defs#labelerViewDetailed":
                self = try .labelerDefsLabelerViewDetailed(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .labelerDefsLabelerView(value):
                try container.encode("app.bsky.labeler.defs#labelerView", forKey: .type)
                try value.encode(to: encoder)
            case let .labelerDefsLabelerViewDetailed(value):
                try container.encode("app.bsky.labeler.defs#labelerViewDetailed", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public indirect enum LabelerGetServices_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func LabelerGetServices(detailed: Bool? = nil, dids: [String]) async throws -> appbskytypes.LabelerGetServices_Output {
        let params: Parameters = ["detailed": .bool(detailed), "dids": .array(dids)]
        do {
            return try await fetch(endpoint: "app.bsky.labeler.getServices", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.LabelerGetServices_Error(error: error)
        }
    }
}
