//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedGetActorFeeds_Output: Codable, Sendable {
        public var cursor: String?
        public var feeds: [FeedDefs_GeneratorView]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, feeds: [FeedDefs_GeneratorView]) {
            self.cursor = cursor
            self.feeds = feeds
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feeds
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.feeds = try keyedContainer.decode([FeedDefs_GeneratorView].self, forKey: .feeds)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.feeds, forKey: .feeds)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetActorFeeds_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetActorFeeds(actor: String, cursor: String? = nil, limit: Int? = nil) async throws -> appbskytypes.FeedGetActorFeeds_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getActorFeeds", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetActorFeeds_Error(error: error)
        }
    }
}
