//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct ActorGetProfiles_Output: Codable, Sendable {
        public var profiles: [ActorDefs_ProfileViewDetailed]
        public let _unknownValues: [String: AnyCodable]

        public init(profiles: [ActorDefs_ProfileViewDetailed]) {
            self.profiles = profiles
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case profiles
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.profiles = try keyedContainer.decode([ActorDefs_ProfileViewDetailed].self, forKey: .profiles)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.profiles, forKey: .profiles)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ActorGetProfiles_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ActorGetProfiles(actors: [String]) async throws -> appbskytypes.ActorGetProfiles_Output {
        let params: Parameters = ["actors": .array(actors)]
        do {
            return try await fetch(endpoint: "app.bsky.actor.getProfiles", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.ActorGetProfiles_Error(error: error)
        }
    }
}
