//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct NotificationGetUnreadCount_Output: Codable, Sendable {
        public var count: Int
        public let _unknownValues: [String: AnyCodable]

        public init(count: Int) {
            self.count = count
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case count
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.count = try keyedContainer.decode(Int.self, forKey: .count)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.count, forKey: .count)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationGetUnreadCount_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func NotificationGetUnreadCount(priority: Bool? = nil, seenAt: String? = nil) async throws -> appbskytypes.NotificationGetUnreadCount_Output {
        let params: Parameters = ["priority": .bool(priority), "seenAt": .string(seenAt)]
        do {
            return try await fetch(endpoint: "app.bsky.notification.getUnreadCount", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.NotificationGetUnreadCount_Error(error: error)
        }
    }
}
