//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct ActorSearchActorsTypeahead_Output: Codable, Sendable {
        public var actors: [ActorDefs_ProfileViewBasic]
        public let _unknownValues: [String: AnyCodable]

        public init(actors: [ActorDefs_ProfileViewBasic]) {
            self.actors = actors
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case actors
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.actors = try keyedContainer.decode([ActorDefs_ProfileViewBasic].self, forKey: .actors)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.actors, forKey: .actors)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ActorSearchActorsTypeahead_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ActorSearchActorsTypeahead(limit: Int? = nil, q: String? = nil, term: String? = nil) async throws -> appbskytypes.ActorSearchActorsTypeahead_Output {
        let params: Parameters = ["limit": .integer(limit), "q": .string(q), "term": .string(term)]
        do {
            return try await fetch(endpoint: "app.bsky.actor.searchActorsTypeahead", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.ActorSearchActorsTypeahead_Error(error: error)
        }
    }
}
