//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedSearchStarterPacksSkeleton_Output: Codable, Sendable {
        public var cursor: String?
        public var hitsTotal: Int?
        public var starterPacks: [UnspeccedDefs_SkeletonSearchStarterPack]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, hitsTotal: Int? = nil, starterPacks: [UnspeccedDefs_SkeletonSearchStarterPack]) {
            self.cursor = cursor
            self.hitsTotal = hitsTotal
            self.starterPacks = starterPacks
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case hitsTotal
            case starterPacks
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.hitsTotal = try keyedContainer.decodeIfPresent(Int.self, forKey: .hitsTotal)
            self.starterPacks = try keyedContainer.decode([UnspeccedDefs_SkeletonSearchStarterPack].self, forKey: .starterPacks)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encodeIfPresent(self.hitsTotal, forKey: .hitsTotal)
            try container.encode(self.starterPacks, forKey: .starterPacks)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedSearchStarterPacksSkeleton_Error: XRPCError {
        case badquerystring(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "BadQueryString":
                self = .badquerystring(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .badquerystring:
                return "BadQueryString"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .badquerystring(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedSearchStarterPacksSkeleton(cursor: String? = nil, limit: Int? = nil, q: String, viewer: String? = nil) async throws -> appbskytypes.UnspeccedSearchStarterPacksSkeleton_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "q": .string(q), "viewer": .string(viewer)]
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.searchStarterPacksSkeleton", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedSearchStarterPacksSkeleton_Error(error: error)
        }
    }
}
