//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct ActorSearchActors_Output: Codable, Sendable {
        public var actors: [ActorDefs_ProfileView]
        public var cursor: String?
        public let _unknownValues: [String: AnyCodable]

        public init(actors: [ActorDefs_ProfileView], cursor: String? = nil) {
            self.actors = actors
            self.cursor = cursor
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case actors
            case cursor
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.actors = try keyedContainer.decode([ActorDefs_ProfileView].self, forKey: .actors)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.actors, forKey: .actors)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ActorSearchActors_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ActorSearchActors(cursor: String? = nil, limit: Int? = nil, q: String? = nil, term: String? = nil) async throws -> appbskytypes.ActorSearchActors_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "q": .string(q), "term": .string(term)]
        do {
            return try await fetch(endpoint: "app.bsky.actor.searchActors", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.ActorSearchActors_Error(error: error)
        }
    }
}
