//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedGetFeedGenerator_Output: Codable, Sendable {
        public var isOnline: Bool
        public var isValid: Bool
        public var view: FeedDefs_GeneratorView
        public let _unknownValues: [String: AnyCodable]

        public init(isOnline: Bool, isValid: Bool, view: FeedDefs_GeneratorView) {
            self.isOnline = isOnline
            self.isValid = isValid
            self.view = view
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case isOnline
            case isValid
            case view
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.isOnline = try keyedContainer.decode(Bool.self, forKey: .isOnline)
            self.isValid = try keyedContainer.decode(Bool.self, forKey: .isValid)
            self.view = try keyedContainer.decode(FeedDefs_GeneratorView.self, forKey: .view)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.isOnline, forKey: .isOnline)
            try container.encode(self.isValid, forKey: .isValid)
            try container.encode(self.view, forKey: .view)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetFeedGenerator_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetFeedGenerator(feed: String) async throws -> appbskytypes.FeedGetFeedGenerator_Output {
        let params: Parameters = ["feed": .string(feed)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getFeedGenerator", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetFeedGenerator_Error(error: error)
        }
    }
}
