//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetLists_Output: Codable, Sendable {
        public var cursor: String?
        public var lists: [GraphDefs_ListView]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, lists: [GraphDefs_ListView]) {
            self.cursor = cursor
            self.lists = lists
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case lists
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.lists = try keyedContainer.decode([GraphDefs_ListView].self, forKey: .lists)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.lists, forKey: .lists)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetLists_Purposes_Elem: RawRepresentable, Codable, Sendable {
        case modlist
        case curatelist
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "modlist":
                self = .modlist
            case "curatelist":
                self = .curatelist
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .modlist:
                "modlist"
            case .curatelist:
                "curatelist"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum GraphGetLists_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetLists(actor: String, cursor: String? = nil, limit: Int? = nil, purposes: [String]? = nil) async throws -> appbskytypes.GraphGetLists_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "limit": .integer(limit), "purposes": .array(purposes)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getLists", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetLists_Error(error: error)
        }
    }
}
