//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedSearchPosts_Output: Codable, Sendable {
        public var cursor: String?
        public var hitsTotal: Int?
        public var posts: [FeedDefs_PostView]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, hitsTotal: Int? = nil, posts: [FeedDefs_PostView]) {
            self.cursor = cursor
            self.hitsTotal = hitsTotal
            self.posts = posts
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case hitsTotal
            case posts
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.hitsTotal = try keyedContainer.decodeIfPresent(Int.self, forKey: .hitsTotal)
            self.posts = try keyedContainer.decode([FeedDefs_PostView].self, forKey: .posts)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encodeIfPresent(self.hitsTotal, forKey: .hitsTotal)
            try container.encode(self.posts, forKey: .posts)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedSearchPosts_Sort: RawRepresentable, Codable, Sendable {
        case top
        case latest
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "top":
                self = .top
            case "latest":
                self = .latest
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .top:
                "top"
            case .latest:
                "latest"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum FeedSearchPosts_Error: XRPCError {
        case badquerystring(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "BadQueryString":
                self = .badquerystring(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .badquerystring:
                return "BadQueryString"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .badquerystring(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedSearchPosts(author: String? = nil, cursor: String? = nil, domain: String? = nil, lang: String? = nil, limit: Int? = nil, mentions: String? = nil, q: String, since: String? = nil, sort: appbskytypes.FeedSearchPosts_Sort? = nil, tag: [String]? = nil, until: String? = nil, url: String? = nil) async throws -> appbskytypes.FeedSearchPosts_Output {
        let params: Parameters = ["author": .string(author), "cursor": .string(cursor), "domain": .string(domain), "lang": .string(lang), "limit": .integer(limit), "mentions": .string(mentions), "q": .string(q), "since": .string(since), "sort": .string(sort?.rawValue), "tag": .array(tag), "until": .string(until), "url": .string(url)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.searchPosts", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedSearchPosts_Error(error: error)
        }
    }
}
