//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct NotificationListNotifications_Notification: Codable, Sendable {
        public var author: ActorDefs_ProfileView
        public var cid: String
        public var indexedAt: String
        public var isRead: Bool
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var reason: NotificationListNotifications_Notification_Reason
        public var reasonSubject: String?
        public var record: LexiconTypeDecoder
        public var uri: String
        public var _unknownValues: [String: AnyCodable]

        public init(author: ActorDefs_ProfileView, cid: String, indexedAt: String, isRead: Bool, labels: [comatprototypes.LabelDefs_Label]? = nil, reason: NotificationListNotifications_Notification_Reason, reasonSubject: String? = nil, record: LexiconTypeDecoder, uri: String) {
            self.author = author
            self.cid = cid
            self.indexedAt = indexedAt
            self.isRead = isRead
            self.labels = labels
            self.reason = reason
            self.reasonSubject = reasonSubject
            self.record = record
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case author
            case cid
            case indexedAt
            case isRead
            case labels
            case reason
            case reasonSubject
            case record
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.author = try keyedContainer.decode(ActorDefs_ProfileView.self, forKey: .author)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.indexedAt = try keyedContainer.decode(String.self, forKey: .indexedAt)
            self.isRead = try keyedContainer.decode(Bool.self, forKey: .isRead)
            self.labels = try keyedContainer.decodeIfPresent([comatprototypes.LabelDefs_Label].self, forKey: .labels)
            self.reason = try keyedContainer.decode(NotificationListNotifications_Notification_Reason.self, forKey: .reason)
            self.reasonSubject = try keyedContainer.decodeIfPresent(String.self, forKey: .reasonSubject)
            self.record = try keyedContainer.decode(LexiconTypeDecoder.self, forKey: .record)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.author, forKey: .author)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.indexedAt, forKey: .indexedAt)
            try container.encode(self.isRead, forKey: .isRead)
            try container.encodeIfPresent(self.labels, forKey: .labels)
            try container.encode(self.reason, forKey: .reason)
            try container.encodeIfPresent(self.reasonSubject, forKey: .reasonSubject)
            try container.encode(self.record, forKey: .record)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationListNotifications_Notification_Reason: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case like
        case repost
        case follow
        case mention
        case reply
        case quote
        case starterpackJoined
        case verified
        case unverified
        case likeViaRepost
        case repostViaRepost
        case subscribedPost
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "like":
                self = .like
            case "repost":
                self = .repost
            case "follow":
                self = .follow
            case "mention":
                self = .mention
            case "reply":
                self = .reply
            case "quote":
                self = .quote
            case "starterpack-joined":
                self = .starterpackJoined
            case "verified":
                self = .verified
            case "unverified":
                self = .unverified
            case "like-via-repost":
                self = .likeViaRepost
            case "repost-via-repost":
                self = .repostViaRepost
            case "subscribed-post":
                self = .subscribedPost
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .like:
                "like"
            case .repost:
                "repost"
            case .follow:
                "follow"
            case .mention:
                "mention"
            case .reply:
                "reply"
            case .quote:
                "quote"
            case .starterpackJoined:
                "starterpack-joined"
            case .verified:
                "verified"
            case .unverified:
                "unverified"
            case .likeViaRepost:
                "like-via-repost"
            case .repostViaRepost:
                "repost-via-repost"
            case .subscribedPost:
                "subscribed-post"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public struct NotificationListNotifications_Output: Codable, Sendable {
        public var cursor: String?
        public var notifications: [NotificationListNotifications_Notification]
        public var priority: Bool?
        public var seenAt: String?
        public var _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, notifications: [NotificationListNotifications_Notification], priority: Bool? = nil, seenAt: String? = nil) {
            self.cursor = cursor
            self.notifications = notifications
            self.priority = priority
            self.seenAt = seenAt
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case notifications
            case priority
            case seenAt
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.notifications = try keyedContainer.decode([NotificationListNotifications_Notification].self, forKey: .notifications)
            self.priority = try keyedContainer.decodeIfPresent(Bool.self, forKey: .priority)
            self.seenAt = try keyedContainer.decodeIfPresent(String.self, forKey: .seenAt)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.notifications, forKey: .notifications)
            try container.encodeIfPresent(self.priority, forKey: .priority)
            try container.encodeIfPresent(self.seenAt, forKey: .seenAt)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationListNotifications_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func NotificationListNotifications(cursor: String? = nil, limit: Int? = nil, priority: Bool? = nil, reasons: [String]? = nil, seenAt: String? = nil) async throws -> appbskytypes.NotificationListNotifications_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "priority": .bool(priority), "reasons": .array(reasons), "seenAt": .string(seenAt)]
        do {
            return try await fetch(endpoint: "app.bsky.notification.listNotifications", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.NotificationListNotifications_Error(error: error)
        }
    }
}
