//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct NotificationUnregisterPush_Input: Codable, Sendable {
        public var appId: String
        public var platform: NotificationUnregisterPush_Input_Platform
        public var serviceDid: String
        public var token: String
        public let _unknownValues: [String: AnyCodable]

        public init(appId: String, platform: NotificationUnregisterPush_Input_Platform, serviceDid: String, token: String) {
            self.appId = appId
            self.platform = platform
            self.serviceDid = serviceDid
            self.token = token
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case appId
            case platform
            case serviceDid
            case token
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.appId = try keyedContainer.decode(String.self, forKey: .appId)
            self.platform = try keyedContainer.decode(NotificationUnregisterPush_Input_Platform.self, forKey: .platform)
            self.serviceDid = try keyedContainer.decode(String.self, forKey: .serviceDid)
            self.token = try keyedContainer.decode(String.self, forKey: .token)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.appId, forKey: .appId)
            try container.encode(self.platform, forKey: .platform)
            try container.encode(self.serviceDid, forKey: .serviceDid)
            try container.encode(self.token, forKey: .token)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationUnregisterPush_Input_Platform: RawRepresentable, Codable, Sendable {
        case ios
        case android
        case web
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "ios":
                self = .ios
            case "android":
                self = .android
            case "web":
                self = .web
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .ios:
                "ios"
            case .android:
                "android"
            case .web:
                "web"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum NotificationUnregisterPush_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func NotificationUnregisterPush(input: appbskytypes.NotificationUnregisterPush_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.notification.unregisterPush", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.NotificationUnregisterPush_Error(error: error)
        }
    }
}
