//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedInitAgeAssurance_Input: Codable, Sendable {
        public var countryCode: String
        public var email: String
        public var language: String
        public let _unknownValues: [String: AnyCodable]

        public init(countryCode: String, email: String, language: String) {
            self.countryCode = countryCode
            self.email = email
            self.language = language
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case countryCode
            case email
            case language
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.countryCode = try keyedContainer.decode(String.self, forKey: .countryCode)
            self.email = try keyedContainer.decode(String.self, forKey: .email)
            self.language = try keyedContainer.decode(String.self, forKey: .language)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.countryCode, forKey: .countryCode)
            try container.encode(self.email, forKey: .email)
            try container.encode(self.language, forKey: .language)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedInitAgeAssurance_Error: XRPCError {
        case didtoolong(String?)
        case invalidemail(String?)
        case invalidinitiation(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "InvalidEmail":
                self = .invalidemail(error.message)
            case "DidTooLong":
                self = .didtoolong(error.message)
            case "InvalidInitiation":
                self = .invalidinitiation(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .invalidemail:
                return "InvalidEmail"
            case .didtoolong:
                return "DidTooLong"
            case .invalidinitiation:
                return "InvalidInitiation"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .invalidemail(message):
                return message
            case let .didtoolong(message):
                return message
            case let .invalidinitiation(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedInitAgeAssurance(input: appbskytypes.UnspeccedInitAgeAssurance_Input) async throws -> appbskytypes.UnspeccedDefs_AgeAssuranceState {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.initAgeAssurance", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedInitAgeAssurance_Error(error: error)
        }
    }
}
