//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct NotificationPutActivitySubscription_Input: Codable, Sendable {
        public var activitySubscription: NotificationDefs_ActivitySubscription
        public var subject: String
        public let _unknownValues: [String: AnyCodable]

        public init(activitySubscription: NotificationDefs_ActivitySubscription, subject: String) {
            self.activitySubscription = activitySubscription
            self.subject = subject
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case activitySubscription
            case subject
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.activitySubscription = try keyedContainer.decode(NotificationDefs_ActivitySubscription.self, forKey: .activitySubscription)
            self.subject = try keyedContainer.decode(String.self, forKey: .subject)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.activitySubscription, forKey: .activitySubscription)
            try container.encode(self.subject, forKey: .subject)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct NotificationPutActivitySubscription_Output: Codable, Sendable {
        public var activitySubscription: NotificationDefs_ActivitySubscription?
        public var subject: String
        public let _unknownValues: [String: AnyCodable]

        public init(activitySubscription: NotificationDefs_ActivitySubscription? = nil, subject: String) {
            self.activitySubscription = activitySubscription
            self.subject = subject
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case activitySubscription
            case subject
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.activitySubscription = try keyedContainer.decodeIfPresent(NotificationDefs_ActivitySubscription.self, forKey: .activitySubscription)
            self.subject = try keyedContainer.decode(String.self, forKey: .subject)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.activitySubscription, forKey: .activitySubscription)
            try container.encode(self.subject, forKey: .subject)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationPutActivitySubscription_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func NotificationPutActivitySubscription(input: appbskytypes.NotificationPutActivitySubscription_Input) async throws -> appbskytypes.NotificationPutActivitySubscription_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.notification.putActivitySubscription", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.NotificationPutActivitySubscription_Error(error: error)
        }
    }
}
