//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedGetConfig_LiveNowConfig: Codable, Sendable {
        public var did: String
        public var domains: [String]
        public let _unknownValues: [String: AnyCodable]

        public init(did: String, domains: [String]) {
            self.did = did
            self.domains = domains
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case did
            case domains
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.domains = try keyedContainer.decode([String].self, forKey: .domains)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.did, forKey: .did)
            try container.encode(self.domains, forKey: .domains)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct UnspeccedGetConfig_Output: Codable, Sendable {
        public var checkEmailConfirmed: Bool?
        public var liveNow: [UnspeccedGetConfig_LiveNowConfig]?
        public let _unknownValues: [String: AnyCodable]

        public init(checkEmailConfirmed: Bool? = nil, liveNow: [UnspeccedGetConfig_LiveNowConfig]? = nil) {
            self.checkEmailConfirmed = checkEmailConfirmed
            self.liveNow = liveNow
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case checkEmailConfirmed
            case liveNow
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.checkEmailConfirmed = try keyedContainer.decodeIfPresent(Bool.self, forKey: .checkEmailConfirmed)
            self.liveNow = try keyedContainer.decodeIfPresent([UnspeccedGetConfig_LiveNowConfig].self, forKey: .liveNow)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.checkEmailConfirmed, forKey: .checkEmailConfirmed)
            try container.encodeIfPresent(self.liveNow, forKey: .liveNow)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetConfig_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedGetConfig() async throws -> appbskytypes.UnspeccedGetConfig_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.getConfig", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedGetConfig_Error(error: error)
        }
    }
}
