//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetStarterPacksWithMembership_Output: Codable, Sendable {
        public var cursor: String?
        public var starterPacksWithMembership: [GraphGetStarterPacksWithMembership_StarterPackWithMembership]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, starterPacksWithMembership: [GraphGetStarterPacksWithMembership_StarterPackWithMembership]) {
            self.cursor = cursor
            self.starterPacksWithMembership = starterPacksWithMembership
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case starterPacksWithMembership
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.starterPacksWithMembership = try keyedContainer.decode([GraphGetStarterPacksWithMembership_StarterPackWithMembership].self, forKey: .starterPacksWithMembership)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.starterPacksWithMembership, forKey: .starterPacksWithMembership)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct GraphGetStarterPacksWithMembership_StarterPackWithMembership: Codable, Sendable {
        public var listItem: GraphDefs_ListItemView?
        public var starterPack: GraphDefs_StarterPackView
        public let _unknownValues: [String: AnyCodable]

        public init(listItem: GraphDefs_ListItemView? = nil, starterPack: GraphDefs_StarterPackView) {
            self.listItem = listItem
            self.starterPack = starterPack
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case listItem
            case starterPack
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.listItem = try keyedContainer.decodeIfPresent(GraphDefs_ListItemView.self, forKey: .listItem)
            self.starterPack = try keyedContainer.decode(GraphDefs_StarterPackView.self, forKey: .starterPack)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.listItem, forKey: .listItem)
            try container.encode(self.starterPack, forKey: .starterPack)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetStarterPacksWithMembership_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetStarterPacksWithMembership(actor: String, cursor: String? = nil, limit: Int? = nil) async throws -> appbskytypes.GraphGetStarterPacksWithMembership_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getStarterPacksWithMembership", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetStarterPacksWithMembership_Error(error: error)
        }
    }
}
