//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedGetPostThreadOtherV2_Output: Codable, Sendable {
        public var thread: [UnspeccedGetPostThreadOtherV2_ThreadItem]
        public var _unknownValues: [String: AnyCodable]

        public init(thread: [UnspeccedGetPostThreadOtherV2_ThreadItem]) {
            self.thread = thread
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case thread
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.thread = try keyedContainer.decode([UnspeccedGetPostThreadOtherV2_ThreadItem].self, forKey: .thread)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.thread, forKey: .thread)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct UnspeccedGetPostThreadOtherV2_ThreadItem: Codable, Sendable {
        public var depth: Int
        public var uri: String
        public var value: UnspeccedGetPostThreadOtherV2_ThreadItem_Value
        public var _unknownValues: [String: AnyCodable]

        public init(depth: Int, uri: String, value: UnspeccedGetPostThreadOtherV2_ThreadItem_Value) {
            self.depth = depth
            self.uri = uri
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case depth
            case uri
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.depth = try keyedContainer.decode(Int.self, forKey: .depth)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.value = try keyedContainer.decode(UnspeccedGetPostThreadOtherV2_ThreadItem_Value.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.depth, forKey: .depth)
            try container.encode(self.uri, forKey: .uri)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetPostThreadOtherV2_ThreadItem_Value: Codable, Sendable {
        case unspeccedDefsThreadItemPost(UnspeccedDefs_ThreadItemPost)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.unspecced.defs#threadItemPost":
                self = try .unspeccedDefsThreadItemPost(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .unspeccedDefsThreadItemPost(value):
                try container.encode("app.bsky.unspecced.defs#threadItemPost", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public indirect enum UnspeccedGetPostThreadOtherV2_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedGetPostThreadOtherV2(anchor: String, prioritizeFollowedUsers: Bool? = nil) async throws -> appbskytypes.UnspeccedGetPostThreadOtherV2_Output {
        let params: Parameters = ["anchor": .string(anchor), "prioritizeFollowedUsers": .bool(prioritizeFollowedUsers)]
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.getPostThreadOtherV2", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedGetPostThreadOtherV2_Error(error: error)
        }
    }
}
