//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedGetTrendingTopics_Output: Codable, Sendable {
        public var suggested: [UnspeccedDefs_TrendingTopic]
        public var topics: [UnspeccedDefs_TrendingTopic]
        public let _unknownValues: [String: AnyCodable]

        public init(suggested: [UnspeccedDefs_TrendingTopic], topics: [UnspeccedDefs_TrendingTopic]) {
            self.suggested = suggested
            self.topics = topics
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case suggested
            case topics
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.suggested = try keyedContainer.decode([UnspeccedDefs_TrendingTopic].self, forKey: .suggested)
            self.topics = try keyedContainer.decode([UnspeccedDefs_TrendingTopic].self, forKey: .topics)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.suggested, forKey: .suggested)
            try container.encode(self.topics, forKey: .topics)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetTrendingTopics_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedGetTrendingTopics(limit: Int? = nil, viewer: String? = nil) async throws -> appbskytypes.UnspeccedGetTrendingTopics_Output {
        let params: Parameters = ["limit": .integer(limit), "viewer": .string(viewer)]
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.getTrendingTopics", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedGetTrendingTopics_Error(error: error)
        }
    }
}
