//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct VideoGetUploadLimits_Output: Codable, Sendable {
        public var canUpload: Bool
        public var error: String?
        public var message: String?
        public var remainingDailyBytes: Int?
        public var remainingDailyVideos: Int?
        public let _unknownValues: [String: AnyCodable]

        public init(canUpload: Bool, error: String? = nil, message: String? = nil, remainingDailyBytes: Int? = nil, remainingDailyVideos: Int? = nil) {
            self.canUpload = canUpload
            self.error = error
            self.message = message
            self.remainingDailyBytes = remainingDailyBytes
            self.remainingDailyVideos = remainingDailyVideos
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case canUpload
            case error
            case message
            case remainingDailyBytes
            case remainingDailyVideos
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.canUpload = try keyedContainer.decode(Bool.self, forKey: .canUpload)
            self.error = try keyedContainer.decodeIfPresent(String.self, forKey: .error)
            self.message = try keyedContainer.decodeIfPresent(String.self, forKey: .message)
            self.remainingDailyBytes = try keyedContainer.decodeIfPresent(Int.self, forKey: .remainingDailyBytes)
            self.remainingDailyVideos = try keyedContainer.decodeIfPresent(Int.self, forKey: .remainingDailyVideos)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.canUpload, forKey: .canUpload)
            try container.encodeIfPresent(self.error, forKey: .error)
            try container.encodeIfPresent(self.message, forKey: .message)
            try container.encodeIfPresent(self.remainingDailyBytes, forKey: .remainingDailyBytes)
            try container.encodeIfPresent(self.remainingDailyVideos, forKey: .remainingDailyVideos)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum VideoGetUploadLimits_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func VideoGetUploadLimits() async throws -> appbskytypes.VideoGetUploadLimits_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.video.getUploadLimits", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.VideoGetUploadLimits_Error(error: error)
        }
    }
}
