//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct NotificationGetPreferences_Output: Codable, Sendable {
        public var preferences: NotificationDefs_Preferences
        public let _unknownValues: [String: AnyCodable]

        public init(preferences: NotificationDefs_Preferences) {
            self.preferences = preferences
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case preferences
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.preferences = try keyedContainer.decode(NotificationDefs_Preferences.self, forKey: .preferences)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.preferences, forKey: .preferences)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationGetPreferences_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func NotificationGetPreferences() async throws -> appbskytypes.NotificationGetPreferences_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.notification.getPreferences", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.NotificationGetPreferences_Error(error: error)
        }
    }
}
