//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedSendInteractions_Input: Codable, Sendable {
        public var interactions: [FeedDefs_Interaction]
        public let _unknownValues: [String: AnyCodable]

        public init(interactions: [FeedDefs_Interaction]) {
            self.interactions = interactions
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case interactions
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.interactions = try keyedContainer.decode([FeedDefs_Interaction].self, forKey: .interactions)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.interactions, forKey: .interactions)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct FeedSendInteractions_Output: Codable, Sendable {
        public let _unknownValues: [String: AnyCodable]

        public init() {
            self._unknownValues = [:]
        }

        public init(from decoder: any Decoder) throws {
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedSendInteractions_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedSendInteractions(input: appbskytypes.FeedSendInteractions_Input) async throws -> appbskytypes.FeedSendInteractions_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.feed.sendInteractions", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedSendInteractions_Error(error: error)
        }
    }
}
