//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetRelationships_Output: Codable, Sendable {
        public var actor: String?
        public var relationships: [GraphGetRelationships_Output_Relationships_Elem]
        public var _unknownValues: [String: AnyCodable]

        public init(actor: String? = nil, relationships: [GraphGetRelationships_Output_Relationships_Elem]) {
            self.actor = actor
            self.relationships = relationships
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case actor
            case relationships
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.actor = try keyedContainer.decodeIfPresent(String.self, forKey: .actor)
            self.relationships = try keyedContainer.decode([GraphGetRelationships_Output_Relationships_Elem].self, forKey: .relationships)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.actor, forKey: .actor)
            try container.encode(self.relationships, forKey: .relationships)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetRelationships_Output_Relationships_Elem: Codable, Sendable {
        case graphDefsRelationship(GraphDefs_Relationship)
        case graphDefsNotFoundActor(GraphDefs_NotFoundActor)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.graph.defs#relationship":
                self = try .graphDefsRelationship(.init(from: decoder))
            case "app.bsky.graph.defs#notFoundActor":
                self = try .graphDefsNotFoundActor(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .graphDefsRelationship(value):
                try container.encode("app.bsky.graph.defs#relationship", forKey: .type)
                try value.encode(to: encoder)
            case let .graphDefsNotFoundActor(value):
                try container.encode("app.bsky.graph.defs#notFoundActor", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public indirect enum GraphGetRelationships_Error: XRPCError {
        case actornotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "ActorNotFound":
                self = .actornotfound(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .actornotfound:
                return "ActorNotFound"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .actornotfound(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetRelationships(actor: String, others: [String]? = nil) async throws -> appbskytypes.GraphGetRelationships_Output {
        let params: Parameters = ["actor": .string(actor), "others": .array(others)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getRelationships", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetRelationships_Error(error: error)
        }
    }
}
