//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetStarterPack_Output: Codable, Sendable {
        public var starterPack: GraphDefs_StarterPackView
        public var _unknownValues: [String: AnyCodable]

        public init(starterPack: GraphDefs_StarterPackView) {
            self.starterPack = starterPack
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case starterPack
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.starterPack = try keyedContainer.decode(GraphDefs_StarterPackView.self, forKey: .starterPack)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.starterPack, forKey: .starterPack)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetStarterPack_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetStarterPack(starterPack: String) async throws -> appbskytypes.GraphGetStarterPack_Output {
        let params: Parameters = ["starterPack": .string(starterPack)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getStarterPack", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetStarterPack_Error(error: error)
        }
    }
}
