//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedGetFeedSkeleton_Output: Codable, Sendable {
        public var cursor: String?
        public var feed: [FeedDefs_SkeletonFeedPost]
        public var reqId: String?
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, feed: [FeedDefs_SkeletonFeedPost], reqId: String? = nil) {
            self.cursor = cursor
            self.feed = feed
            self.reqId = reqId
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feed
            case reqId
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.feed = try keyedContainer.decode([FeedDefs_SkeletonFeedPost].self, forKey: .feed)
            self.reqId = try keyedContainer.decodeIfPresent(String.self, forKey: .reqId)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.feed, forKey: .feed)
            try container.encodeIfPresent(self.reqId, forKey: .reqId)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetFeedSkeleton_Error: XRPCError {
        case unknownfeed(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "UnknownFeed":
                self = .unknownfeed(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .unknownfeed:
                return "UnknownFeed"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unknownfeed(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetFeedSkeleton(cursor: String? = nil, feed: String, limit: Int? = nil) async throws -> appbskytypes.FeedGetFeedSkeleton_Output {
        let params: Parameters = ["cursor": .string(cursor), "feed": .string(feed), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getFeedSkeleton", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetFeedSkeleton_Error(error: error)
        }
    }
}
