//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public indirect enum FeedGetAuthorFeed_Filter: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case postsWithReplies
        case postsNoReplies
        case postsWithMedia
        case postsAndAuthorThreads
        case postsWithVideo
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "posts_with_replies":
                self = .postsWithReplies
            case "posts_no_replies":
                self = .postsNoReplies
            case "posts_with_media":
                self = .postsWithMedia
            case "posts_and_author_threads":
                self = .postsAndAuthorThreads
            case "posts_with_video":
                self = .postsWithVideo
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .postsWithReplies:
                "posts_with_replies"
            case .postsNoReplies:
                "posts_no_replies"
            case .postsWithMedia:
                "posts_with_media"
            case .postsAndAuthorThreads:
                "posts_and_author_threads"
            case .postsWithVideo:
                "posts_with_video"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public struct FeedGetAuthorFeed_Output: Codable, Sendable {
        public var cursor: String?
        public var feed: [FeedDefs_FeedViewPost]
        public var _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, feed: [FeedDefs_FeedViewPost]) {
            self.cursor = cursor
            self.feed = feed
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feed
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.feed = try keyedContainer.decode([FeedDefs_FeedViewPost].self, forKey: .feed)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.feed, forKey: .feed)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetAuthorFeed_Error: XRPCError {
        case blockedactor(String?)
        case blockedbyactor(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "BlockedActor":
                self = .blockedactor(error.message)
            case "BlockedByActor":
                self = .blockedbyactor(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .blockedactor:
                return "BlockedActor"
            case .blockedbyactor:
                return "BlockedByActor"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .blockedactor(message):
                return message
            case let .blockedbyactor(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetAuthorFeed(actor: String, cursor: String? = nil, filter: appbskytypes.FeedGetAuthorFeed_Filter? = nil, includePins: Bool? = nil, limit: Int? = nil) async throws -> appbskytypes.FeedGetAuthorFeed_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "filter": .string(filter?.rawValue), "includePins": .bool(includePins), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getAuthorFeed", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetAuthorFeed_Error(error: error)
        }
    }
}
