//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct VideoGetJobStatus_Output: Codable, Sendable {
        public var jobStatus: VideoDefs_JobStatus
        public let _unknownValues: [String: AnyCodable]

        public init(jobStatus: VideoDefs_JobStatus) {
            self.jobStatus = jobStatus
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case jobStatus
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.jobStatus = try keyedContainer.decode(VideoDefs_JobStatus.self, forKey: .jobStatus)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.jobStatus, forKey: .jobStatus)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum VideoGetJobStatus_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func VideoGetJobStatus(jobId: String) async throws -> appbskytypes.VideoGetJobStatus_Output {
        let params: Parameters = ["jobId": .string(jobId)]
        do {
            return try await fetch(endpoint: "app.bsky.video.getJobStatus", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.VideoGetJobStatus_Error(error: error)
        }
    }
}
