//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedGetTimeline_Output: Codable, Sendable {
        public var cursor: String?
        public var feed: [FeedDefs_FeedViewPost]
        public var _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, feed: [FeedDefs_FeedViewPost]) {
            self.cursor = cursor
            self.feed = feed
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feed
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.feed = try keyedContainer.decode([FeedDefs_FeedViewPost].self, forKey: .feed)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.feed, forKey: .feed)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetTimeline_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetTimeline(algorithm: String? = nil, cursor: String? = nil, limit: Int? = nil) async throws -> appbskytypes.FeedGetTimeline_Output {
        let params: Parameters = ["algorithm": .string(algorithm), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getTimeline", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetTimeline_Error(error: error)
        }
    }
}
