//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedGetSuggestedUsersSkeleton_Output: Codable, Sendable {
        public var dids: [String]
        public let _unknownValues: [String: AnyCodable]

        public init(dids: [String]) {
            self.dids = dids
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case dids
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.dids = try keyedContainer.decode([String].self, forKey: .dids)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.dids, forKey: .dids)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetSuggestedUsersSkeleton_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedGetSuggestedUsersSkeleton(category: String? = nil, limit: Int? = nil, viewer: String? = nil) async throws -> appbskytypes.UnspeccedGetSuggestedUsersSkeleton_Output {
        let params: Parameters = ["category": .string(category), "limit": .integer(limit), "viewer": .string(viewer)]
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.getSuggestedUsersSkeleton", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedGetSuggestedUsersSkeleton_Error(error: error)
        }
    }
}
