//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetFollowers_Output: Codable, Sendable {
        public var cursor: String?
        public var followers: [ActorDefs_ProfileView]
        public var subject: ActorDefs_ProfileView
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, followers: [ActorDefs_ProfileView], subject: ActorDefs_ProfileView) {
            self.cursor = cursor
            self.followers = followers
            self.subject = subject
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case followers
            case subject
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.followers = try keyedContainer.decode([ActorDefs_ProfileView].self, forKey: .followers)
            self.subject = try keyedContainer.decode(ActorDefs_ProfileView.self, forKey: .subject)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.followers, forKey: .followers)
            try container.encode(self.subject, forKey: .subject)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetFollowers_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetFollowers(actor: String, cursor: String? = nil, limit: Int? = nil) async throws -> appbskytypes.GraphGetFollowers_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getFollowers", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetFollowers_Error(error: error)
        }
    }
}
