//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedGetTaggedSuggestions_Output: Codable, Sendable {
        public var suggestions: [UnspeccedGetTaggedSuggestions_Suggestion]
        public var _unknownValues: [String: AnyCodable]

        public init(suggestions: [UnspeccedGetTaggedSuggestions_Suggestion]) {
            self.suggestions = suggestions
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case suggestions
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.suggestions = try keyedContainer.decode([UnspeccedGetTaggedSuggestions_Suggestion].self, forKey: .suggestions)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.suggestions, forKey: .suggestions)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct UnspeccedGetTaggedSuggestions_Suggestion: Codable, Sendable {
        public var subject: String
        public var subjectType: UnspeccedGetTaggedSuggestions_Suggestion_SubjectType
        public var tag: String
        public var _unknownValues: [String: AnyCodable]

        public init(subject: String, subjectType: UnspeccedGetTaggedSuggestions_Suggestion_SubjectType, tag: String) {
            self.subject = subject
            self.subjectType = subjectType
            self.tag = tag
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case subject
            case subjectType
            case tag
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.subject = try keyedContainer.decode(String.self, forKey: .subject)
            self.subjectType = try keyedContainer.decode(UnspeccedGetTaggedSuggestions_Suggestion_SubjectType.self, forKey: .subjectType)
            self.tag = try keyedContainer.decode(String.self, forKey: .tag)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.subject, forKey: .subject)
            try container.encode(self.subjectType, forKey: .subjectType)
            try container.encode(self.tag, forKey: .tag)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetTaggedSuggestions_Suggestion_SubjectType: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case actor
        case feed
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "actor":
                self = .actor
            case "feed":
                self = .feed
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .actor:
                "actor"
            case .feed:
                "feed"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetTaggedSuggestions_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedGetTaggedSuggestions() async throws -> appbskytypes.UnspeccedGetTaggedSuggestions_Output {
        let params: Bool? = nil
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.getTaggedSuggestions", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedGetTaggedSuggestions_Error(error: error)
        }
    }
}
