//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct UnspeccedGetPostThreadV2_Output: Codable, Sendable {
        public var hasOtherReplies: Bool
        public var thread: [UnspeccedGetPostThreadV2_ThreadItem]
        public var threadgate: FeedDefs_ThreadgateView?
        public var _unknownValues: [String: AnyCodable]

        public init(hasOtherReplies: Bool, thread: [UnspeccedGetPostThreadV2_ThreadItem], threadgate: FeedDefs_ThreadgateView? = nil) {
            self.hasOtherReplies = hasOtherReplies
            self.thread = thread
            self.threadgate = threadgate
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case hasOtherReplies
            case thread
            case threadgate
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.hasOtherReplies = try keyedContainer.decode(Bool.self, forKey: .hasOtherReplies)
            self.thread = try keyedContainer.decode([UnspeccedGetPostThreadV2_ThreadItem].self, forKey: .thread)
            self.threadgate = try keyedContainer.decodeIfPresent(FeedDefs_ThreadgateView.self, forKey: .threadgate)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.hasOtherReplies, forKey: .hasOtherReplies)
            try container.encode(self.thread, forKey: .thread)
            try container.encodeIfPresent(self.threadgate, forKey: .threadgate)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetPostThreadV2_Sort: RawRepresentable, Codable, Sendable {
        public typealias RawValue = String

        case newest
        case oldest
        case top
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "newest":
                self = .newest
            case "oldest":
                self = .oldest
            case "top":
                self = .top
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .newest:
                "newest"
            case .oldest:
                "oldest"
            case .top:
                "top"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public struct UnspeccedGetPostThreadV2_ThreadItem: Codable, Sendable {
        public var depth: Int
        public var uri: String
        public var value: UnspeccedGetPostThreadV2_ThreadItem_Value
        public var _unknownValues: [String: AnyCodable]

        public init(depth: Int, uri: String, value: UnspeccedGetPostThreadV2_ThreadItem_Value) {
            self.depth = depth
            self.uri = uri
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case depth
            case uri
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.depth = try keyedContainer.decode(Int.self, forKey: .depth)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.value = try keyedContainer.decode(UnspeccedGetPostThreadV2_ThreadItem_Value.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.depth, forKey: .depth)
            try container.encode(self.uri, forKey: .uri)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetPostThreadV2_ThreadItem_Value: Codable, Sendable {
        case unspeccedDefsThreadItemPost(UnspeccedDefs_ThreadItemPost)
        case unspeccedDefsThreadItemNoUnauthenticated(UnspeccedDefs_ThreadItemNoUnauthenticated)
        case unspeccedDefsThreadItemNotFound(UnspeccedDefs_ThreadItemNotFound)
        case unspeccedDefsThreadItemBlocked(UnspeccedDefs_ThreadItemBlocked)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.unspecced.defs#threadItemPost":
                self = try .unspeccedDefsThreadItemPost(.init(from: decoder))
            case "app.bsky.unspecced.defs#threadItemNoUnauthenticated":
                self = try .unspeccedDefsThreadItemNoUnauthenticated(.init(from: decoder))
            case "app.bsky.unspecced.defs#threadItemNotFound":
                self = try .unspeccedDefsThreadItemNotFound(.init(from: decoder))
            case "app.bsky.unspecced.defs#threadItemBlocked":
                self = try .unspeccedDefsThreadItemBlocked(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .unspeccedDefsThreadItemPost(value):
                try container.encode("app.bsky.unspecced.defs#threadItemPost", forKey: .type)
                try value.encode(to: encoder)
            case let .unspeccedDefsThreadItemNoUnauthenticated(value):
                try container.encode("app.bsky.unspecced.defs#threadItemNoUnauthenticated", forKey: .type)
                try value.encode(to: encoder)
            case let .unspeccedDefsThreadItemNotFound(value):
                try container.encode("app.bsky.unspecced.defs#threadItemNotFound", forKey: .type)
                try value.encode(to: encoder)
            case let .unspeccedDefsThreadItemBlocked(value):
                try container.encode("app.bsky.unspecced.defs#threadItemBlocked", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public indirect enum UnspeccedGetPostThreadV2_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func UnspeccedGetPostThreadV2(above: Bool? = nil, anchor: String, below: Int? = nil, branchingFactor: Int? = nil, prioritizeFollowedUsers: Bool? = nil, sort: appbskytypes.UnspeccedGetPostThreadV2_Sort? = nil) async throws -> appbskytypes.UnspeccedGetPostThreadV2_Output {
        let params: Parameters = ["above": .bool(above), "anchor": .string(anchor), "below": .integer(below), "branchingFactor": .integer(branchingFactor), "prioritizeFollowedUsers": .bool(prioritizeFollowedUsers), "sort": .string(sort?.rawValue)]
        do {
            return try await fetch(endpoint: "app.bsky.unspecced.getPostThreadV2", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.UnspeccedGetPostThreadV2_Error(error: error)
        }
    }
}
