//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedGetLikes_Like: Codable, Sendable {
        public var actor: ActorDefs_ProfileView
        public var createdAt: String
        public var indexedAt: String
        public var _unknownValues: [String: AnyCodable]

        public init(actor: ActorDefs_ProfileView, createdAt: String, indexedAt: String) {
            self.actor = actor
            self.createdAt = createdAt
            self.indexedAt = indexedAt
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case actor
            case createdAt
            case indexedAt
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.actor = try keyedContainer.decode(ActorDefs_ProfileView.self, forKey: .actor)
            self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
            self.indexedAt = try keyedContainer.decode(String.self, forKey: .indexedAt)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.actor, forKey: .actor)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.indexedAt, forKey: .indexedAt)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct FeedGetLikes_Output: Codable, Sendable {
        public var cid: String?
        public var cursor: String?
        public var likes: [FeedGetLikes_Like]
        public var uri: String
        public var _unknownValues: [String: AnyCodable]

        public init(cid: String? = nil, cursor: String? = nil, likes: [FeedGetLikes_Like], uri: String) {
            self.cid = cid
            self.cursor = cursor
            self.likes = likes
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case cursor
            case likes
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decodeIfPresent(String.self, forKey: .cid)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.likes = try keyedContainer.decode([FeedGetLikes_Like].self, forKey: .likes)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cid, forKey: .cid)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.likes, forKey: .likes)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetLikes_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetLikes(cid: String? = nil, cursor: String? = nil, limit: Int? = nil, uri: String) async throws -> appbskytypes.FeedGetLikes_Output {
        let params: Parameters = ["cid": .string(cid), "cursor": .string(cursor), "limit": .integer(limit), "uri": .string(uri)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getLikes", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetLikes_Error(error: error)
        }
    }
}
