//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public indirect enum ActorGetProfile_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func ActorGetProfile(actor: String) async throws -> appbskytypes.ActorDefs_ProfileViewDetailed {
        let params: Parameters = ["actor": .string(actor)]
        do {
            return try await fetch(endpoint: "app.bsky.actor.getProfile", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.ActorGetProfile_Error(error: error)
        }
    }
}
