//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct FeedGetPosts_Output: Codable, Sendable {
        public var posts: [FeedDefs_PostView]
        public let _unknownValues: [String: AnyCodable]

        public init(posts: [FeedDefs_PostView]) {
            self.posts = posts
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case posts
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.posts = try keyedContainer.decode([FeedDefs_PostView].self, forKey: .posts)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.posts, forKey: .posts)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedGetPosts_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func FeedGetPosts(uris: [String]) async throws -> appbskytypes.FeedGetPosts_Output {
        let params: Parameters = ["uris": .array(uris)]
        do {
            return try await fetch(endpoint: "app.bsky.feed.getPosts", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.FeedGetPosts_Error(error: error)
        }
    }
}
