//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetSuggestedFollowsByActor_Output: Codable, Sendable {
        public var isFallback: Bool?
        public var recId: Int?
        public var suggestions: [ActorDefs_ProfileView]
        public let _unknownValues: [String: AnyCodable]

        public init(isFallback: Bool? = nil, recId: Int? = nil, suggestions: [ActorDefs_ProfileView]) {
            self.isFallback = isFallback
            self.recId = recId
            self.suggestions = suggestions
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case isFallback
            case recId
            case suggestions
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.isFallback = try keyedContainer.decodeIfPresent(Bool.self, forKey: .isFallback)
            self.recId = try keyedContainer.decodeIfPresent(Int.self, forKey: .recId)
            self.suggestions = try keyedContainer.decode([ActorDefs_ProfileView].self, forKey: .suggestions)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.isFallback, forKey: .isFallback)
            try container.encodeIfPresent(self.recId, forKey: .recId)
            try container.encode(self.suggestions, forKey: .suggestions)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetSuggestedFollowsByActor_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetSuggestedFollowsByActor(actor: String) async throws -> appbskytypes.GraphGetSuggestedFollowsByActor_Output {
        let params: Parameters = ["actor": .string(actor)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getSuggestedFollowsByActor", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetSuggestedFollowsByActor_Error(error: error)
        }
    }
}
