//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public struct GraphGetList_Output: Codable, Sendable {
        public var cursor: String?
        public var items: [GraphDefs_ListItemView]
        public var list: GraphDefs_ListView
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, items: [GraphDefs_ListItemView], list: GraphDefs_ListView) {
            self.cursor = cursor
            self.items = items
            self.list = list
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case items
            case list
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.items = try keyedContainer.decode([GraphDefs_ListItemView].self, forKey: .items)
            self.list = try keyedContainer.decode(GraphDefs_ListView.self, forKey: .list)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.items, forKey: .items)
            try container.encode(self.list, forKey: .list)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum GraphGetList_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }
}
extension XRPCClientProtocol {
    public mutating func GraphGetList(cursor: String? = nil, limit: Int? = nil, list: String) async throws -> appbskytypes.GraphGetList_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "list": .string(list)]
        do {
            return try await fetch(endpoint: "app.bsky.graph.getList", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw appbskytypes.GraphGetList_Error(error: error)
        }
    }
}
